.github/workflows/go.yml, go.mod, go.sum
This should make Docker Hub builds happy too, as it is running the make file currently.
=> Fix make file and run make in GitHub Actions

test/e2e/e2e_test.go, test/e2e/restclient.go, test/e2e/run.sh, test/e2e/stack.go
This is the first Go module I've ever written, so help me out here.
Naming and placement of this file are also up for discussion.
Would also like to have at least one other person test this before merging. Note that it currently doesn't work with the `master` version of [firefly-cli](https://github.com/kaleido-io/firefly-cli) due to some bugs - awaiting fixes from @nguyer on that.
=> Add basic E2E test

README.md
Realized we're missing the cross-links in the README
=> Add links to the other repos

pkg/database/plugin.go
- allows transaction queries to be filtered by namespace
=> add namespace filter to TransactionFactory

internal/blockchain/ethereum/ethereum.go, internal/blockchain/ethereum/ethereum_test.go
=> Rename kld query strings

Dockerfile
=> Update GitHub URL for firefly-ui

docs/keyconcepts/proposal.md
Signed-off-by: Nick Gaski <nick.gaski@kaleido.io>
=> fix proposal link

README.md
=> Add README link for firefly-samples

docs/Gemfile.lock
See https://github.com/hyperledger-labs/firefly/security/dependabot/docs/Gemfile.lock/addressable/open
=> Update addressable in Gemfile.lock for vulnerability

internal/privatemessaging/recipients.go
This fixes a case where we saw repeated `groupinit` messages being sent every time an unpinned message exchange was being performed in a request/reply scenario between two parties in the network.
The problem was the "_does the group already exist?_" check was being done using DB query with a hash calculated on an _unsorted_ list of members. Whereas the creation was correctly using `group.Seal()` which sorts the list of members before hashing. So we would repeat the creation over and over.
=> Repeated groupinit messages: Make sure we sort the group members, before existence check

Dockerfile, internal/blockchain/ethereum/ethereum.go, solidity_firefly/contracts/Payment.sol
Couple of standalone cleanup items identified while working #124. Might as well put them in while the larger development effort is still ongoing.
Depends on https://github.com/hyperledger-labs/firefly-cli/pull/66
=> Misc cleanup surrounding Solidity contracts

docs/swagger/swagger.yaml, internal/oapispec/openapi3.go
=> Fix Swagger description of Request-Timeout param

Makefile
=> Don't pollute go.mod when running "make test"

internal/assets/manager.go, internal/assets/manager_test.go, internal/tokens/https/https.go, internal/tokens/https/https_test.go, mocks/tokenmocks/plugin.go, pkg/tokens/plugin.go
Depends on https://github.com/hyperledger-labs/firefly-tokens-erc1155/pull/18
=> Supply requestId when creating token pools

Dockerfile
=> bump ui to version 0.3.1

docs/gettingstarted/broadcast_data.md
Signed-off-by: scaraclette <gustiscarlett@gmail.com>
=> Fixed endpoint typo to send blob

internal/tokens/fftokens/fftokens.go, internal/tokens/fftokens/fftokens_test.go, manifest.json
=> Always pass key and message hash to fftokens connector

manifest.json
=> Update dependencies for v0.11.0 release

internal/database/sqlcommon/tokenbalance_sql.go
=> Return an empty slice (rather than nil) for zero token accounts

.golangci.yml
For consideration - this seems to reduce the overhead significantly.
=> Reduce overhead of gocritic

internal/blockchain/fabric/eventstream.go, internal/blockchain/fabric/fabric_test.go
See conversation in https://github.com/hyperledger/firefly-fabconnect/pull/63
=> Fabric connector needs to subscribe from zero

internal/config/config.go, internal/config/config_test.go
Signed-off-by: jebonfig <joe.bonfiglio@kaleido.io>
=> Support configuration keys when the value type is a list

manifest.json
=> Update manifest ready for v0.11.3 release

.golangci.yml
=> Allow any company name in license header

pkg/wsclient/wsclient.go
If a receiver sends a new websocket message while processing a received message, and
the send fails, the code can deadlock with the send and receive loops waiting on each
other.
=> Prevent send/receive deadlock in wsclient

pkg/wsclient/wsclient_test.go
Addresses coverage drop from #387
=> Fix unit test for wsclient send failure

test/e2e/e2e_test.go
Signed-off-by: jebonfig <joe.bonfiglio@kaleido.io>
=> Build the URL without the firefly port if it was omitted from stack.json

test/e2e/fabric_contract_test.go
Resolves https://github.com/hyperledger/firefly/issues/423
=> Fix intermittent Fabric E2E test failure

pkg/fftypes/jsonany.go, pkg/fftypes/jsonany_test.go
=> Allow calling JSONObject() on nil JSONAny

internal/apiserver/route_post_token_mint.go, internal/tokens/fftokens/fftokens.go
Some connectors may support (or require) this.
=> Allow passing a tokenIndex to "mint"

manifest.json, manifestgen.sh
Signed-off-by: David Echelberger <david.echelberger@kaleido.io>
=> [v0.12.0-manifests] manifests for v0.12.0

manifest.json
=> Update EthConnect to 3.1.3

docs/swagger/swagger.yaml, pkg/database/plugin.go
Signed-off-by: David Echelberger <eberger727@gmail.com>
=> [transfer-type-query] allow filtering by type on token transfers

internal/oapiffi/ffi2swagger.go
Resolves https://github.com/hyperledger/firefly/issues/540
=> Change query method to POST for custom contracts

docs/gettingstarted/broadcast_data.md, docs/gettingstarted/custom_blockchain.md, docs/gettingstarted/define_datatype.md, docs/gettingstarted/events.md, docs/gettingstarted/private_send.md, docs/gettingstarted/query_messages.md, docs/keyconcepts/data_exchange.md, docs/swagger/swagger.yaml, internal/apiserver/swagger_check_test.go, internal/apiserver/swagger_generate_test.go
Adds a build fix to https://github.com/hyperledger/firefly/pull/451
=> Documentation updates from @TheSwarnim

docs/gettingstarted/broadcast_data.md, docs/gettingstarted/custom_blockchain.md, docs/gettingstarted/define_datatype.md, docs/gettingstarted/events.md, docs/gettingstarted/private_send.md, docs/gettingstarted/query_messages.md, docs/keyconcepts/data_exchange.md, docs/swagger/swagger.yaml
I've added some changes in firefly documentation which I think will make it more useful and informative.
=> Updated documentation to make it more useful

manifest.json, pkg/fftypes/batch.go, pkg/fftypes/contracts.go, pkg/fftypes/datatype.go, pkg/fftypes/event.go, pkg/fftypes/identity.go, pkg/fftypes/message.go, pkg/fftypes/namespace.go, pkg/fftypes/offset.go, pkg/fftypes/operation.go, pkg/fftypes/tokenpool.go, pkg/fftypes/tokentransfer.go, pkg/fftypes/transaction.go, pkg/fftypes/transport_wrapper.go, pkg/fftypes/verifier.go, pkg/fftypes/websocket_actions.go
=> Dependency updates for v0.14 testing

manifest.json
=> Update microservices versions for v0.14.0

manifest.json
Signed-off-by: David Echelberger <eberger727@gmail.com>
=> [ui-v0.6.0-release] new ui release

internal/tokens/fftokens/fftokens.go, internal/tokens/fftokens/fftokens_test.go
Enables https://github.com/hyperledger/firefly-tokens-erc20-erc721/pull/36
=> Add pool config to activate call

manifest.json
Signed-off-by: David Echelberger <eberger727@gmail.com>
=> [ui-v0.6.3] v0.6.3 release of ui in manifest

internal/config/config.go, internal/events/batch_pin_complete_test.go, internal/events/blockchain_event.go, internal/events/blockchain_event_test.go, internal/events/token_pool_created_test.go, internal/events/tokens_approved_test.go, internal/events/tokens_transferred_test.go, internal/txcommon/event_enrich.go, internal/txcommon/txcommon.go, internal/txcommon/txcommon_test.go, mocks/txcommonmocks/helper.go
Based on this flame graph analysis:
=> Cache blockchain events for event enrichment

docs/swagger/swagger.yaml, internal/apiserver/route_post_new_message_broadcast.go, internal/apiserver/route_post_new_message_private.go
Signed-off-by: Gabriel Indik <gabriel.indik@kaleido.io>
=> Update txType in private message schema

internal/batch/batch_processor.go
Tweak to the logic from #650 - the assumption made in the code was invalid on assuming a value of `0` was enough to determine if we needed to use `INSERT` (vs. `UPDATE`) for the `nonces` collection. 
Because if multiple private messages go into a batch, this value will be incremented.
=> Cannot assume zero as reason to insert vs. update

internal/events/token_pool_created.go, internal/events/token_pool_created_test.go, internal/orchestrator/txn_status.go, internal/orchestrator/txn_status_test.go, internal/tokens/fftokens/fftokens.go, internal/tokens/fftokens/fftokens_test.go
Requires matching changes in all token connectors as well.
=> Clean up blockchain parameters returned by token connectors

.github/workflows/docker_release.yml, manifest.json
=> Update manifest for v1.0.0-rc.1

.github/workflows/docker_release.yml
=> Fix make docker command in release build GitHub Action

internal/oapiffi/ffi2swagger.go, internal/oapiffi/ffi2swagger_test.go
=> Parse input params for /query endpoints in ffi2swagger

cmd/firefly.go, internal/orchestrator/orchestrator_test.go, pkg/config/config.go, pkg/config/config_test.go
=> Allow config suffix to be changed by microservices using config package

internal/assets/token_pool.go, internal/assets/token_pool_test.go, internal/events/token_pool_created.go, internal/events/token_pool_created_test.go, internal/tokens/fftokens/fftokens.go, internal/tokens/fftokens/fftokens_test.go
=> Resolve pool activation operations more cleanly

internal/database/sqlcommon/tokenapproval_sql.go, internal/database/sqlcommon/tokenapproval_sql_test.go, internal/database/sqlcommon/tokenpool_sql.go
=> Token approvals should return empty array instead of nil

internal/adminevents/manager_test.go, internal/blockchain/ethereum/config.go, internal/blockchain/ethereum/ethereum.go, internal/blockchain/fabric/config.go, internal/blockchain/fabric/fabric.go, internal/dataexchange/ffdx/config.go, internal/dataexchange/ffdx/ffdx.go, internal/events/websockets/websockets_test.go, internal/tokens/fftokens/config.go, internal/tokens/fftokens/fftokens.go, manifest.json, pkg/wsclient/wsconfig.go, pkg/wsclient/wsconfig_test.go
=> Merge wsconfig to wsclient so microservices can use it

internal/events/blockchain_event.go
=> Fill in blockchain TX ID for contract listener events

docs/swagger/swagger.yaml, mocks/contractmocks/manager.go, mocks/databasemocks/plugin.go, pkg/fftypes/tokenpool.go
This is currently a read-only field.
=> "decimals" is not a valid input

pkg/i18n/en_base_error_messages.go
=> Add prefix for signer

manifest.json
=> Update manifest.json for v1.0.0

db/migrations/postgres/000086_alter_contractapis.down.sql, db/migrations/postgres/000086_alter_contractapis.up.sql, db/migrations/sqlite/000086_alter_contractapis.down.sql, db/migrations/sqlite/000086_alter_contractapis.up.sql, test/e2e/ethereum_contract_test.go, test/e2e/restclient_test.go
Looks like release-1.0 was based off of the wrong commit, so a few fixes in 1.0.0 actually didn't make it onto the release branch. Need to bring these in before doing any patch releases so that we don't regress.
=> Merge v1.0.0 history

internal/assets/manager.go, internal/batch/batch_manager.go, internal/batchpin/batchpin.go, internal/broadcast/manager.go, internal/contracts/manager.go, internal/coremsgs/en_error_messages.go, internal/data/data_manager.go, internal/definitions/definition_handler.go, internal/events/event_manager.go, internal/identity/identitymanager.go, internal/networkmap/manager.go, internal/operations/manager.go, internal/privatemessaging/privatemessaging.go, internal/shareddownload/download_manager.go
I needed this briefly for debugging; might as well keep it around.
=> Include component name when initialization fails

internal/blockchain/ethereum/ethereum_test.go, internal/blockchain/fabric/fabric_test.go
Unintentional coverage drop from #819
=> Address coverage gap for "Capabilities" method

README.md
I found a few links were missing, and given how many repos we've grown to I proposed a bit of organization too.
=> Update README with missing links, and bit of a restructure

manifest.json, smart_contracts/ethereum/solidity_firefly/contracts/Firefly.sol, smart_contracts/fabric/firefly-go/chaincode/contract.go
Minor fixes to stabilize main ahead of the next alpha release.
=> Restore FireFly contract version, update UI version

.github/workflows/docker_release.yml
=> Fix github.ref in prereleased action

manifest.json
Signed-off-by: Alex Shorsher <alex.shorsher@kaleido.io>
=> update token connector versions

Dockerfile
It's helpful to have this handy when debugging database contents.
=> Add sqlite to Docker image

manifest.json
UI is fully functional again with latest mainline code.
=> Update UI version

internal/operations/operation_updater_test.go
=> Fix test coverage gaps in operations manager

docs/tutorials/broadcast_data.md
Thank you :) 
Signed-off-by: Jeff <60796676+JeffNeff@users.noreply.github.com>
=> Fixes Incorrect Route in the `broadcast_data`Tutorial

docs/reference/events.md
discard if you want
Signed-off-by: sebgoa <runseb@gmail.com>
=> super small typo

internal/database/sqlite3/sqlite3.go
=> Wait up to 1000ms to lock sqlite database

docs/contributors/dev_environment_setup.md
Update the example command to match the latest folder structure.
=> fixing the example firefly core command

go.mod, go.sum
=> Update to firefly-signer v0.9.13

go.mod, go.sum
=> Update to firefly-signer v0.9.15

internal/events/event_manager.go
=> Add nil check for blobReceiver during WaitStop

manifest.json
=> Manifest updates for v1.1.0-rc.1

.github/workflows/go.yml, manifest.json
Also adds two evmconnect configurations to the test matrix
=> Update CLI to v1.1.0-rc.1

test/e2e/multiparty/multi_tenancy.go
=> Ensure new namespaces are up during multi_tenancy test

docs/reference/api_post_syntax.md, docs/reference/api_query_syntax.md, docs/reference/events.md, docs/reference/firefly_interface_format.md, docs/reference/identities.md, docs/reference/index.md
See live preview at https://awrichar.github.io/firefly/head/reference/identities.html
=> Add reference doc on identities

manifest.json, manifestgen.sh
=> Add firefly-signer to manifest

test/e2e/run.sh
Signed-off-by: Anna Jackson <anna.jackson@kaleido.io>
Fixes #1011
=> add another account for fabric

docs/swagger/swagger.yaml, docs/tutorials/custom_contracts/ethereum.md, docs/tutorials/events.md, internal/apiserver/route_get_contract_listener_by_name_or_id.go, internal/apiserver/route_get_contract_listener_by_name_or_id_test.go, internal/apiserver/route_get_subscription_by_id.go, internal/apiserver/route_get_subscription_by_id_test.go, internal/blockchain/ethereum/ethereum.go, internal/blockchain/ethereum/ethereum_test.go, internal/blockchain/ethereum/eventstream.go, internal/blockchain/fabric/fabric.go, internal/blockchain/fabric/fabric_test.go, internal/contracts/manager.go, internal/contracts/manager_test.go, internal/coremsgs/en_api_translations.go, internal/coremsgs/en_error_messages.go, internal/orchestrator/orchestrator.go, internal/orchestrator/subscriptions.go, internal/orchestrator/subscriptions_test.go, mocks/blockchainmocks/plugin.go, mocks/contractmocks/manager.go, mocks/orchestratormocks/orchestrator.go, pkg/blockchain/plugin.go, pkg/core/contract_listener.go, pkg/core/subscription.go
in a chain with #1028 
not currently published on my github pages due to hosting another doc changes.
=> update event docs

internal/identity/identitymanager.go, internal/identity/identitymanager_test.go
=> remove legacy namespace query for organizations

manifest.json
=> Update manifest for v1.1.0-rc.3

internal/blockchain/ethereum/address_resolver_test.go, internal/blockchain/ethereum/ethereum_test.go, internal/blockchain/fabric/fabric_test.go, internal/data/data_manager_test.go, internal/events/aggregator_test.go, internal/events/event_manager_test.go, internal/identity/identitymanager_test.go, internal/operations/manager_test.go, internal/orchestrator/orchestrator_test.go, internal/privatemessaging/privatemessaging_test.go, internal/txcommon/txcommon_test.go
Fix coverage decrement introduced by central cache PR.
Signed-off-by: Chengxuan Xing <chengxuan.xing@kaleido.io>
=> adding test cases for cache init errors

internal/blockchain/ethereum/ethereum.go, internal/blockchain/ethereum/ethereum_test.go, manifest.json
See https://github.com/hyperledger/firefly-transaction-manager/pull/36
> Leaving in draft mode until we have an FFTM+EVMConnect release, to include in the manifest
=> Handle FFTM new style acks with batchNumber

manifest.json
=> Update manifest for v1.1.0

docker_build.sh
=> Load output of docker buildx

docs/tutorials/create_custom_identity.md
Signed-off-by: David Echelberger <eberger727@gmail.com>
=> [identity-docs-formatting] removing newline

internal/definitions/handler_identity_claim.go, internal/definitions/handler_identity_update.go, internal/definitions/handler_identity_update_test.go
=> V1.1.x/mainline fix: Allow update of node using parent org identity

docs/_i18n/en.yml, docs/faqs/index.md, docs/releasenotes/index.md
Added release notes and FF 1.1 migration guide
Signed-off-by: aznrayizzle <ray.chen@kaleido.io>
=> release notes

.github/workflows/docker_release.yml
=> Fix Docker Release GitHub Action

.github/workflows/docker_main.yml, .github/workflows/docker_release.yml
=> Use new steps in Docker GitHub Actions

docs/reference/microservices/fftokens.md, docs/reference/microservices/index.md, docs/reference/namespaces.md
=> Add docs on fftokens

docs/tutorials/custom_contracts/ethereum.md
Signed-off-by: Chengxuan Xing <chengxuan.xing@kaleido.io>
=> Update example script

go.mod, go.sum
=> Update to firefly-common@v1.2.1

internal/apiserver/route_get_op_by_id_test.go, internal/orchestrator/data_query.go, internal/orchestrator/data_query_test.go, internal/orchestrator/orchestrator.go, manifest.json, mocks/orchestratormocks/orchestrator.go, pkg/core/operation.go
Resolves https://github.com/hyperledger/firefly/issues/1149
=> Rename operation detailedStatus to detail

docs/overview/public_vs_permissioned.md
added back public vs. permissioned page
=> public vs. permissioned page

internal/events/persist_batch.go
=> Allow receiving a message with no data

manifest.json, test/e2e/multiparty/tokens.go, test/e2e/run.sh
=> Update dependencies for v1.2.0

internal/events/webhooks/webhooks_test.go
=> Fix coverage gap in webhooks test

.github/workflows/integration.yml
=> Add stack type to nightly integration tests

manifest.json
=> Update UI and CLI to v1.2.0

cmd/firefly.go
for https://github.com/hyperledger/firefly/pull/1194#discussion_r1114651400
=> remove redundant reset

.github/workflows/docker_main.yml, .github/workflows/docker_release.yml, .github/workflows/go.yml, .github/workflows/integration.yml, Dockerfile, cmd/firefly.go, docker_build.sh
Resolves https://github.com/hyperledger/firefly/issues/1186
Resolves https://github.com/hyperledger/firefly/issues/1187 and should address all of the warnings we currently have in our GitHub action runs
=> Add version to log output and fix Dockerfile to include it

internal/database/sqlcommon/operation_sql_test.go, internal/operations/manager_test.go
Address missing coverage from #1257
=> Fix coverage gaps from new operation update logic

docs/tutorials/chains/polygon_testnet.md
Update the RPC endpoint URLs in the readme
=> Update rpc endpoints in polygon_testnet.md 

.github/workflows/integration.yml
We are in a beta for large runners, and I want to see if this workflow is faster using them.
=> Try out large runners to see if they are faster.

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/other-issue.md
Adding some issue templates to guide people to Discord for questions and support.
=> Add GitHub issue templates

internal/definitions/sender_contracts.go
Resolves https://github.com/hyperledger/firefly/issues/1274
=> Fix updating Contract APIs

db/migrations/postgres/000108_create_contractapis_id_index.down.sql, db/migrations/postgres/000108_create_contractapis_id_index.up.sql, db/migrations/sqlite/000108_create_contractapis_id_index.down.sql, db/migrations/sqlite/000108_create_contractapis_id_index.up.sql, internal/database/sqlcommon/contractapis_sql.go
Ensure that insert and update are executed correctly, and add a unique index on ID.
=> Add proper WHERE clause to contract API updates

internal/definitions/handler_datatype_test.go, internal/definitions/handler_identity_claim_test.go, internal/definitions/handler_identity_update_test.go, internal/definitions/handler_identity_verification_test.go, internal/definitions/handler_network_node_test.go, internal/definitions/handler_network_org_test.go, internal/definitions/handler_tokenpool_test.go, internal/definitions/sender_datatype_test.go, internal/definitions/sender_identity_test.go, internal/definitions/sender_tokenpool_test.go
=> Clean up remaining definition tests

go.mod, go.sum, pkg/core/contracts.go, pkg/core/contracts_test.go, pkg/core/tokenpool.go, pkg/core/tokenpool_test.go
Fixes #1349
Related fix that will also need to be integrated: https://github.com/hyperledger/firefly-common/pull/76
=> Use NetworkName instead of Name for definition topics

docs/reference/microservices/fftokens.md
New API added to fftokens API spec by these PRs:
https://github.com/hyperledger/firefly-tokens-erc20-erc721/pull/136
https://github.com/hyperledger/firefly-tokens-erc1155/pull/125
=> Add fftokens docs on /deactivatepool

internal/apiserver/route_post_new_contract_api.go, internal/batch/batch_manager.go, internal/batch/batch_manager_test.go, internal/batch/batch_processor.go, internal/batch/batch_processor_test.go, internal/blockchain/ethereum/ethereum.go, internal/definitions/sender_contracts.go, manifest.json
Backport of the following fixes:
https://github.com/hyperledger/firefly/pull/1249
https://github.com/hyperledger/firefly/pull/1275
https://github.com/hyperledger/firefly/pull/1313
https://github.com/hyperledger/firefly/pull/1316
=> v1.2: Backport fixes

internal/txcommon/txcommon.go, internal/txcommon/txcommon_test.go
Ensure that the "event" corresponding to each "blockchain event" always gets created, even in the case that a batch insert of blockchain events failed (partially) and caused a fallback to the row-by-row insert.
Fixes #1376
=> Detect partial success when performing batch insert of blockchain events
