Dockerfile
This change significantly reduces the size of the published Docker container, down to ~30MB from ~950MB. It also includes compiled solidity contracts in the image which can be installed if needed.
=> Use multi-stage Docker build. Compile contracts into image.

.gitignore, Dockerfile, internal/apiserver/server.go, internal/apiserver/ui.go, internal/config/config.go
This PR adds the ability to serve a static HTML/CSS/JS frontend, if enabled in the config. This repo does not contain a frontend, so the config file will need to point to some place on the filesystem that a compiled frontend exists.
The following entry in `firefly.core` will serve HTML files from a directory called `frontend`.
```yaml
ui:
path: frontend
```
> **NOTE**: The frontend is **not** enabled by default. If no `ui.path` key is present in the config file, the frontend will not be served.
The Dockerfile has also been updated to build the latest commit of https://github.com/kaleido-io/firefly-ui and include that in the image.
=> Serve frontend

go.mod, test/e2e/run.sh
As of Go 1.16, "go install" is the cleanest way to install global
tools without messing up go.mod
See https://maelvls.dev/go111module-everywhere
=> Use "go install" instead of "go get" for installing CLI

Makefile
I've run several successful builds locally while limiting my Docker VM's memory to 1.5 GB so I'm pretty confident this will work in Docker Hub where the limit is 2.0 GB.
=> Lower memory limit in Makefile to fix Docker Hub builds

Makefile
I think we're just over the default threshold of 1 minute for `golangci-lint` when we run it in Docker Hub. Likely caused by reducing its memory usage, it runs more slowly now than it used to. This should get it to build in Docker Hub again.
=> Increase linter timeout to 5m

.dockerignore, Dockerfile
Move tool installs before local builds, and add Solidity build
output to .dockerignore.
=> Minor Docker build optimizations

.github/workflows/docker.yml, .github/workflows/go.yml
This PR adds a new GitHub Action that builds and pushes Docker images to GitHub Container Repository.
It also re-enables our normal PR checks after the repo was transferred.
=> Add Docker Build GitHub Action

pkg/database/plugin.go
` "error": "FF10148: Unknown filter 'namespace'"` when querying operations on API
=> Add namespace to operation filter factory

test/e2e/e2e_test.go, test/e2e/restclient.go, test/e2e/run.sh
This gets the E2E test running again with the latest API. Can (should) be run manually before commits with `./test/e2e/run.sh`. Eventually will get it added to a GitHub action as well.
It's not as clean or as thorough as it could be, but it's a start. Feedback/future suggestions welcome.
=> Fix E2E test

cmd/firefly.go
This should fix default values not getting applied at startup.
=> Call Reset() before reading config on startup

db/migrations/ql/000004_create_batches_table.up.sql
This fixes an inconsistent DB constraint between the QL schema and the PostgreSQL schema, which is causing errors when using QL.
=> Fix QL migration for batches

internal/blockchain/ethereum/config.go, internal/blockchain/ethereum/ethereum.go, internal/blockchain/ethereum/ethereum_test.go
This PR adds configuration options for the `ethconnect` plugin:
- `shortPrefix`: used in query parameters in requests to `ethconnect`
- `longPrefix`: used in x-headers in requests to `ethconnect` if headers are used in the future
=> Add config options for ethconnect prefix

go.mod, go.sum, internal/orchestrator/config.go, internal/orchestrator/config_test.go
This fixes HTTP requests sometimes failing when resetting FireFly after a config change.
=> Wait to reset parent context after HTTP request context finishes

internal/blockchain/ethereum/ethereum.go, internal/blockchain/ethereum/ethereum_test.go, internal/privatemessaging/message.go
Currently if you send an unpinned message, it is correctly marked `pending: false` (with a confirmed timestamp) on the receiving node(s), but the sending node leaves it forever in a `pending` state on the sender.
This means in the UI, all the requests are shown _before_ the replies 🙃 
The problem was the unpinned send code was setting `pending` and `confirmed` _before_ sealing the message, which then reset those back to default.
=> Fix pending unpinned sends

test/e2e/e2e_test.go
#94 fixed the order of the request and reply, but the e2e test was depending on the incorrect order (noting natural sort order is newest first)
=> Fix ordering of message checks in TestE2EWebhookExchangeNoTx

docs/swagger/swagger.md
Previously the CSS for the Swagger UI was being overriden by the Jekyll theme. This made code blocks look like this:
These changes fix the CSS so the Swagger theme is preserved and they now look like this:
=> Fix CSS on swagger docs

internal/batch/batch_processor.go, internal/database/sqlcommon/sqlcommon.go, test/e2e/e2e_test.go, test/e2e/run.sh, test/e2e/stack.go
Resolves https://github.com/hyperledger-labs/firefly/issues/121
This PR adds the ability to run the E2E tests against any FireFly environment. If someone wants to run the tests against a remote FireFly (not on their local dev machine) they will need to create or modify a `stack.json` file to add some new fields that are not currently added by the CLI. These changes are still backwards compatible with existing `stack.json` files created by the CLI.
Here's an example of a new `stack.json` file that points to remote FireFly instances and also uses HTTPS and basic authentication.
```json
{
"name": "dev",
"members": [
{
"id": "0",
"index": 0,
"address": "0xac9c1260fb2ad017de65ce7cf68c0142903357ab",
"privateKey": "0x02e9b8465ea1b585c2050b1fdf2fbe642c92b74192a0fb6f403ce2d91b5f5fdc", …
```
=> E2E Enhancements

docs/gettingstarted/broadcast_data.md, docs/gettingstarted/private_send.md, docs/swagger/swagger.yaml, pkg/fftypes/message.go, pkg/fftypes/message_test.go
In a message header, previously there was a field named `topic` but it was of type `[]string`. It makes more sense to call this field `topics` because it is a list of several topic names. This PR changes this, but it is important to note that this is an API breaking change (though small in size).
Example message:
```json
{
"header": {
"tag": "new_widget_created",
"topics": ["widget_id_12345"]
},
"data": [
{
"value": {
"id": "widget_id_12345",
"name": "superwidget"
}
}
]
}
```
=> Rename topic field to topics

internal/config/config.go, internal/events/event_poller.go
Early adopter feedback suggests that latency of event delivery is more important than throughput optimization, in the most common scenarios. Particularly in non-blockchain backed event scenarios, and even more in request/reply scenarios.
Currently we use a 250ms default latency on event delivery, to reduce pressure on the DB in high throughput scenarios by giving time for messages to arrive between queries.
This PR proposes making the default 0, optimizing for latency by default (before we cut the first release).
=> Latency optimize event delivery by default

internal/events/aggregator.go, internal/events/aggregator_test.go, internal/events/event_dispatcher.go, internal/events/event_manager.go, internal/events/event_poller.go, internal/events/event_poller_test.go
Fix for https://github.com/hyperledger-labs/firefly/issues/134
Fixes two problems:
1. If we break out of the loop for leadership election before we start the event poller, then `close` will hang as it was waiting on `eventPoller.closed`.
- No need for `ed.close` to wait on that, it can just wait on `ed.closed`
2. We were not handling errors from `eventPoller.start()`
- Added retry for restoring the offset, and stopped it from returning an error in the case that the context is closed before it starts - it simply marks itself closed.
=> Retry for errors on event poller startup, and only wait for ep close in one place

internal/events/aggregator.go, internal/events/aggregator_test.go, internal/events/event_dispatcher.go, internal/events/event_manager.go, internal/events/event_poller.go, internal/events/event_poller_test.go, internal/events/websockets/websocket_connection.go, internal/events/websockets/websockets.go, internal/events/websockets/websockets_test.go
This made encountering #134 really likely for the app under test, as it was subscribing to one durable subscription, then immediately subscribing to another.
However, because the `webSocketsConnection` only allowed a single subscription in the matcher, that second subscribe was actually causing subscription manager to close the first subscription (as it no longer matched the connection).
Note in a PR chain with #135 (which is the fix for the deadlock in #134)
=> Allow multiple durable subscriptions to be started on a single websocket

docs/gettingstarted/private_send.md, internal/privatemessaging/message.go, internal/privatemessaging/message_test.go
Currently we have a difference between unpinned and pinned private messaging:
- Pinned private messages emit a `message_confirmed` on _all_ members when the blockchain TX completes
- Unpinned messages emit a `message_confirmed` on all members _except_ the sender when they arrive
- Originally it was thought this might be less confusing than emitting a message locally in the unpinned case.
- We've found that it's actually more confusing. Particularly as it means that if you have a request/response messaging scenario via FireFly it changes the behavior of whether the locally connected apps get triggered or not.
With this PR in place, we become consistent.
- Pinned private messages emit a `message_confirmed` on _all_ members when the blockchain TX completes
- Unpinned messages emit a …
=> Emit events for locally produced unpinned private messages

internal/events/subscription_manager.go, internal/events/webhooks/webhooks.go, internal/events/webhooks/webhooks_test.go
- Fixes #115 - webhook subscriptions not working after restart
- The problem here was that the submanager was initializing after Webhooks had registered the global connection, and the code was assuming no connections existed at the time submanager was starting. So it wasn't starting the dispatchers.
- Fixes an error where webhook message delivery stop functioning after the following error is logged:
```
DEBUG Webhook subscription with reply enabled called with reply event '1cb8bc49-40e6-4496-bb96-620527d5eca9' pid=1
```
- Here the problem was the loop detection code missing an ack on the event, so no further events were being delivered.
=> Fix sequencing of submgr/webhooks and fix loop detection

internal/events/event_dispatcher.go, internal/events/event_dispatcher_test.go
Encountered the below deadlock with a zero readahead connection, where we can see:
- The `eventLoop` routine is waiting in `bufferedDelivery` to push message 2 of 3 into `eventDelivery` channel
- The `deliverEvents` routine is stuck in `deliveryResponse` trying to notify the the `eventLoop`
The architecture is intended to avoid this deadlock, by having a channel big enough that the `eventLoop` can always get all `dispatchable` events into it.
In the logs before the hang, I can see `matched=3` `dispatchable=3`.
This _should_ indicate that the readahead is at least 2, which means the channel should have 3 slots in it.
```
[2021-07-19T18:29:04.086Z] DEBUG Dispatcher event state: candidates=3 matched=3 inflight=0 queued=0 dispatched=0 dispatchable=3 lastAck=0 nacks=0 highest=25 pid=1 …
```
=> Fix dispatcher deadlock when using custom readahead

internal/database/sqlcommon/group_sql.go, internal/database/sqlcommon/message_sql.go, internal/events/batch_pin_complete.go, internal/events/batch_pin_complete_test.go, internal/events/persist_batch.go, pkg/fftypes/jsondata.go, pkg/fftypes/jsondata_test.go
We saw a situation where broadcasts were not being processed by a network, and the reason logged was:
```
[2021-07-21T13:29:22.474Z] DEBUG Message 29ef8ae6-06a0-461c-b9d1-fa754e6f3315 pinned at sequence 11775 blocked by earlier context f80c0fb74bf21261afe26836caeb7fa4569580b5ba07f2cf35f4a645d000769d at sequence 10667 dbtx=oWj1wBCU pid=1 role=aggregator
```
This was in a FireFly environment where it had been rebuilt, with fresh FireFly databases, but using the same on-chain contract. The context of the batches that could not be processed were organizataion definitions.
Inspecting the `pins` database table, we could see a list of un-dispatched pins for the same context (e.g. the same on-chain organization ID):
```
seq  | masked |                               hash …
```
=> Avoid writing pins that can never be resolved

test/e2e/restclient.go
The E2E tests expect members to be listed in the same order as they appear in the `stack.json` file. This change queries the API, asking it to sort the members in the expected order.
=> Fix E2E tests with more than 3 members

internal/blockchain/ethereum/ethereum.go, internal/blockchain/ethereum/ethereum_test.go, internal/broadcast/manager.go, internal/broadcast/manager_test.go, internal/events/event_manager.go, internal/events/transaction_update.go, internal/events/transaction_update_test.go, internal/orchestrator/bound_callbacks.go, internal/privatemessaging/privatemessaging.go, internal/privatemessaging/privatemessaging_test.go, mocks/blockchainmocks/callbacks.go, mocks/blockchainmocks/plugin.go, mocks/eventmocks/event_manager.go, pkg/blockchain/plugin.go
Counterpart to https://github.com/hyperledger-labs/firefly-ethconnect/pull/139.
This will reduce the noisy logs when using tokens, because tokens generates ethconnect events that are "unexpected" from the perspective of the blockchain plugin. There will still be a single warning printed for each token transaction, but that's...a little better?
=> Remove retry for correlating transactions

internal/syncasync/sync_async_bridge.go, internal/syncasync/sync_async_bridge_test.go
This changeset simplifies the `inflightRequest` interface and adds 3 new generic constructs:
* `inflightResponse`
* `requestType`
* `requestSender`
The core helpers of sync-async (`sendAndWait` and `eventCallback`) now deal with these generic types and perform much less messaging-specific inspection of the requests and responses. There are clearer extension points for new request-response flows that may or may not relate to messaging at all.
The end goal is that this will make it easier to wrap tokens (and other future operations) in sync-async handlers.
=> Make sync-async helpers less specific to messaging

internal/broadcast/manager.go, internal/broadcast/message.go, internal/privatemessaging/message.go, internal/privatemessaging/privatemessaging.go, internal/syncasync/sync_async_bridge.go, internal/syncasync/sync_async_bridge_test.go, internal/syshandlers/syshandler.go, internal/syshandlers/syshandler_test.go, internal/sysmessaging/msgsender.go, mocks/broadcastmocks/manager.go, mocks/privatemessagingmocks/manager.go, mocks/syshandlersmocks/system_handlers.go, mocks/sysmessagingmocks/message_sender.go
Given the method naming, it feels more intuitive to pass this in (rather
than requiring the sender to set it on a nested field before invoking).
=> Add an "id" parameter to SendMessageWithID

internal/tokens/https/https.go
Counterpart to the field renames in https://github.com/hyperledger-labs/firefly-tokens-erc1155/pull/15. E2E tests are expected to fail until that PR is merged and released as a Docker image.
=> Rename token fields to match backend changes

CODEOWNERS
This should fix the issue of requiring Nick's approval for anything that touches `/docs`. The intention was that he _could_ approve anything that _only_ modified `/docs`, but the way `CODEOWNERS` works, only the last rule to match gets applied, which meant global owners couldn't approve anything in `/docs`. I think this is the simplest solution to achieve what we want.
=> Add maintainers as CODEOWNERS for /docs

Makefile
Generating mocks can be sped up significantly by splitting each file out
as a separate target and using e.g. "make mocks -j8".
=> Support multi-threaded "make mocks"

internal/blockchain/ethereum/ethereum.go, internal/blockchain/ethereum/ethereum_test.go, internal/tokens/https/https.go, internal/tokens/https/https_test.go
Both will contain keys for blockNumber, transactionIndex, and transactionHash
(at least on Ethereum). Prune higher and lower level nested items from the
JSON body.
=> Align the "additional info" for blockchain and token transactions

db/migrations/postgres/000028_add_tokenpool_fields.down.sql, db/migrations/postgres/000028_add_tokenpool_fields.up.sql, db/migrations/sqlite/000028_add_tokenpool_fields.down.sql, db/migrations/sqlite/000028_add_tokenpool_fields.up.sql, docs/swagger/swagger.yaml, internal/apiserver/route_post_token_pool.go, internal/database/sqlcommon/tokenpool_sql.go, internal/database/sqlcommon/tokenpool_sql_test.go, internal/orchestrator/orchestrator.go, internal/tokens/https/https.go, internal/tokens/https/https_test.go, mocks/tokenmocks/plugin.go, pkg/database/plugin.go, pkg/fftypes/tokenpool.go, pkg/tokens/plugin.go
All token pools should record the connector that created them, may optionally
include a token symbol, and may (in the near future) be linked to a message.
=> Add additional fields to TokenPool

internal/orchestrator/orchestrator.go, internal/tokens/fftokens/config.go, internal/tokens/fftokens/fftokens.go, internal/tokens/fftokens/fftokens_test.go, internal/tokens/tifactory/factory.go, pkg/tokens/config.go
The name "https" is too generic - the plugin represents a way to map token operations
like pool, mint, and transfer into a specific HTTP+websocket protocol. Therefore a
specific, unique name is appropriate.
Also changed the config key from "connector" to "plugin" (since its purpose is to
affect which plugin FireFly loads from the map).
Added migration paths for both changes so that the CLI and any existing stacks can
have time to be updated.
=> Rename tokens "https" plugin to "fftokens"

docs/swagger/swagger.yaml, internal/apiserver/route_post_data.go, internal/data/data_manager.go, internal/orchestrator/orchestrator_test.go, pkg/fftypes/byteable.go, pkg/fftypes/byteable_test.go, pkg/fftypes/data.go, pkg/fftypes/data_test.go, pkg/fftypes/datatype.go, test/e2e/e2e_test.go, test/e2e/restclient.go
Fix for #198 
- Fixes handling of `null` on `data.value` - including as part of a FORM post upload
- Stored as the bytes `null` in the database (as today)
- Does not contribute to the hash, when there is a blob
- Returned as `null` in the JSON payload on `GET`
- Adds a new `validator` of `none`
- Must be set explicitly - `json` remains the default
- Disabled any checking of the `datatype.name`/`datatype.value` when set
- Allows you to just use the `datatype` for tagging purposes, without validating the `value` JSON payload itself
=> Allow null value with blob data, and allow "none" validator to tag datatype on unstructured data

internal/data/blobstore.go, internal/data/blobstore_test.go, internal/data/data_manager.go, pkg/fftypes/data.go, pkg/fftypes/data_test.go
In testing #207 we found the following error when using `validator: "none"` on a JSON upload of `data`, that was not seen on the BLOB upload.
```
FF10200: Unknown validator type: ‘none’
```
I found a discrepancy in the validation on upload between the two paths. This PR should reconcile that.
=> Consistency in JSON/Blob codepaths for validation of "none" datatype

db/migrations/postgres/000008_create_operations_table.up.sql, db/migrations/sqlite/000008_create_operations_table.up.sql, docs/swagger/swagger.yaml, internal/assets/manager.go, internal/assets/manager_test.go, internal/assets/token_pool_created.go, internal/assets/token_pool_created_test.go, internal/broadcast/manager.go, internal/broadcast/tokenpool.go, internal/broadcast/tokenpool_test.go, internal/orchestrator/bound_callbacks.go, internal/orchestrator/bound_callbacks_test.go, internal/orchestrator/orchestrator.go, internal/syshandlers/syshandler.go, internal/syshandlers/syshandler_test.go, internal/syshandlers/syshandler_tokenpool.go, internal/syshandlers/syshandler_tokenpool_test.go, internal/tokens/fftokens/fftokens.go, internal/tokens/fftokens/fftokens_test.go, mocks/assetmocks/manager.go, mocks/broadcastmocks/manager.go, mocks/tokenmocks/callbacks.go, pkg/fftypes/constants.go, pkg/fftypes/operation.go, pkg/fftypes/tokenpool.go, pkg/fftypes/tokenpool_test.go, pkg/tokens/plugin.go
Rather than requiring all token pool metadata (namespace, name, id) to be written
to the blockchain, send it out via a broadcast message after creating the actual
pool on chain.
~~Note: this contains the commit from #210 as a pre-req.~~
=> Announce token pool info via broadcast

internal/events/webhooks/webhooks.go, internal/events/webhooks/webhooks_test.go
Support plain string as a message value in webhook subscription.  
**Observed behavior**
When putting a plain string in the value field of a FireFly message, the HTTP request body on the received webhook is an empty object
**Expected behavior:**
If a message is accepted by a FireFly node, whatever is in the value field should be put in the HTTP request body for a webhook subscription
**Before Changes:**
POST /test HTTP/1.1
Host: ff-meera.requestcatcher.com
Accept: application/json
Accept-Encoding: gzip
Content-Length: 2
Content-Type: application/json
User-Agent: go-resty/2.6.0 (https://github.com/go-resty/resty)
{}
**After Changes.**
POST /test HTTP/1.1
Host: ff-meera.requestcatcher.com
Accept: application/json
Accept-Encoding: gzip
Content-Length: 20
Content-Type: application/json …
=> Support plain string as a message value in webhook subscription

test/e2e/onchain_offchain_test.go
Even though these tests use confirm=true, we must create a websocket
and wait on events to propagate (otherwise the events may propagate
later and confuse the next test).
Fixes #308
=> Consume websocket events in "strong datatype" tests

internal/blockchain/ethereum/config.go, internal/blockchain/ethereum/ethereum.go, internal/blockchain/ethereum/ethereum_test.go, internal/blockchain/fabric/config.go, internal/blockchain/fabric/fabric.go, internal/blockchain/fabric/fabric_test.go
This was previously used by the CLI as a temporary way to bring up FireFly
without initializing event streams - but bringup has been streamlined in
other ways now that do not require it.
=> Remove "skipEventstreamInit" parameters

internal/apiserver/server.go, internal/apiserver/server_test.go, internal/batchpin/batchpin.go, internal/batchpin/batchpin_test.go, internal/metrics/metrics.go
Adds `BatchPinCounter` prometheus metric, which will be incremented each time a `batchpin` is submitted
=> add batchpin counter prometheus metric

db/migrations/postgres/000047_add_token_uri_fields.down.sql, db/migrations/postgres/000047_add_token_uri_fields.up.sql, db/migrations/sqlite/000047_add_token_uri_fields.down.sql, db/migrations/sqlite/000047_add_token_uri_fields.up.sql, docs/swagger/swagger.yaml, internal/apiserver/route_post_token_burn.go, internal/apiserver/route_post_token_burn_by_type.go, internal/apiserver/route_post_token_mint.go, internal/apiserver/route_post_token_mint_by_type.go, internal/apiserver/route_post_token_transfer.go, internal/apiserver/route_post_token_transfer_by_type.go, internal/database/sqlcommon/tokenbalance_sql.go, internal/database/sqlcommon/tokenbalance_sql_test.go, internal/database/sqlcommon/tokentransfer_sql.go, internal/database/sqlcommon/tokentransfer_sql_test.go, internal/events/tokens_transferred_test.go, internal/tokens/fftokens/fftokens.go, manifest.json, pkg/database/plugin.go, pkg/fftypes/tokenbalance.go, pkg/fftypes/tokentransfer.go
Depends on https://github.com/hyperledger/firefly-tokens-erc1155/pull/44
Resolves #326
=> Add token URI

docs/gettingstarted/mint_tokens.md, docs/gettingstarted/setup_env.md
Initial docs for #218.
~~Some of the routes described here are still being updated by @eberger727 in #307, so should wait for that PR before merging this.~~
I've published the docs in this PR to my own FireFly fork here, if you like reading the pretty pages instead of the Markdown: https://awrichar.github.io/firefly/gettingstarted/mint_tokens.html
=> Add "Getting Started" documentation for tokens

internal/events/tokens_transferred.go, internal/events/tokens_transferred_test.go, internal/tokens/fftokens/fftokens.go, internal/tokens/fftokens/fftokens_test.go, manifest.json
Depends on https://github.com/hyperledger/firefly-tokens-erc1155/pull/45 (E2E tests will fail without this)
=> Leverage new token transfer id from plugin

deploy/charts/firefly/Chart.yaml, deploy/charts/firefly/templates/core/secret.yaml, deploy/charts/firefly/templates/core/statefulset.yaml, deploy/charts/firefly/values.yaml, internal/i18n/en_translations.go
Noticed these when trying to deploy FireFly in live environments via the Helm chart
* `psql_url` needs to be a key in the `firefly-config` `Secret` when using the migration job
* uses for `ghcr.io/hyperledger/` for Docker repos
* no longer uses `latest` image tag, and instead uses `v0.9.2` for DX and `.Chart.AppVersion` for FF (which is set to `v0.11.1`)
* error message for when `organization.key` is not set is misleading since it reference the deprecated `organization.identity`
=> Fix Hyperledger Image Refs and Migration Job's Postgres URL in Helm Chart

deploy/charts/firefly/README.md, deploy/charts/firefly/values.yaml
Helm chart still had `-labs` in the names
=> Fix image repos

docs/swagger/swagger.yaml, go.mod, go.sum, internal/apiserver/route_post_new_subscription.go, internal/oapispec/openapi3.go, internal/oapispec/openapi3_test.go
- Depends on https://github.com/getkin/kin-openapi/pull/451
- Needs the `go.mod` replace stripping out before it can move out of draft
- Corrects a bug where we weren't honouring the `ffenum` etc. tags on outputs (only inputs)
=> Updates to handle recursive structures in swagger - depends on kin-openapi change

internal/oapispec/openapi3_test.go
Coverage for JSONInputMask was inadvertently lost.
=> Address coverage drop from #337

internal/assets/token_transfer.go, internal/assets/token_transfer_test.go
Previously, if a tokens related transaction failed the transaction and operation in the DB would stay in the pending state. Now, it will correctly be marked as `failed`
=> on transfer/mint/burn fail, set transaction & operation as failed

internal/assets/token_pool.go, internal/assets/token_pool_test.go, internal/assets/token_transfer.go, internal/assets/token_transfer_test.go, internal/batchpin/batchpin.go, internal/batchpin/batchpin_test.go, internal/broadcast/manager.go, internal/broadcast/manager_test.go, internal/database/sqlcommon/operation_sql.go, internal/database/sqlcommon/operation_sql_test.go, internal/events/token_pool_created.go, internal/events/token_pool_created_test.go, internal/privatemessaging/privatemessaging.go, internal/privatemessaging/privatemessaging_test.go, mocks/databasemocks/plugin.go, pkg/database/plugin.go
No code path ever passes allowExisting=true, and we already have a separate
UpdateOperation method for updates. Therefore, rename this method to
InsertOperation and remove the unneeded branches.
=> Replace UpsertOperation with InsertOperation

deploy/charts/firefly/templates/dataexchange/statefulset.yaml, deploy/charts/firefly/values.yaml
We aren't ensuring there's some sort of writeable filesystem to the DX pods for blob storage, might as well offer the ability to persist it too. This refactors how we template the DX PVCs to other more customization (size, storage class, etc.) for future users, as well as offers the ability to disable the PVCs and use `emptyDir` instead.
> **NOTE**: This does include a breaking change in the chart for how DX data is handled: `/data/peers` and `/data/peer-certs` are now apart of the same PVC but given subdirs within the volume. However, we have not made an official release of the chart yet.
=> [helm] Adding Storage for DX Blobs and PVC Templating Improvements

docs/swagger/swagger.yaml, internal/apiserver/route_get_group_by_id.go, internal/apiserver/route_get_group_by_id_test.go, internal/apiserver/route_get_groups.go, internal/apiserver/route_get_groups_test.go, internal/apiserver/routes.go, internal/definitions/definition_handler.go, internal/definitions/definition_handler_test.go, internal/identity/identitymanager.go, internal/identity/identitymanager_test.go, internal/orchestrator/status.go, internal/orchestrator/status_test.go, internal/privatemessaging/groupmanager.go, internal/privatemessaging/groupmanager_test.go, internal/privatemessaging/message_test.go, internal/privatemessaging/privatemessaging.go, internal/privatemessaging/privatemessaging_test.go, manifest.json, mocks/definitionsmocks/definition_handlers.go, mocks/identitymanagermocks/manager.go, mocks/privatemessagingmocks/manager.go
I noticed that when I was only sending to myself, I was still getting data being pushed by FireFly core to DX.
Looks like when we made the identity change to introduce DIDs, we broke the code here:
https://github.com/hyperledger/firefly/blob/24d075b4ec5b08601780ebac04fefc61aebbd427/internal/privatemessaging/privatemessaging.go#L188-L191
Also @hfuss mentioned to me that we've seen problems where the config has to have the full Key specification exactly as it gets resolved by the blockchain connector (so `0x` prefix for ethereum, and the full `CN=xyz...` syntax for fabric), or things do not work correctly.
This PR:
- Ensures we always use the blockchain connector to get the resolved signing key
- Compares `Owner` of a `Node` to the signing key of the local org, not the DID
- Adds APIs to …
=> Fix send-to-self for private messages, and add group query URLs

.github/workflows/helm.yml, deploy/charts/firefly/ci/it-values.yaml, deploy/charts/firefly/templates/_helpers.tpl, deploy/charts/firefly/templates/core/service.yaml, deploy/charts/firefly/templates/core/servicemonitor.yaml, deploy/charts/firefly/templates/core/statefulset.yaml, deploy/charts/firefly/templates/dataexchange/statefulset.yaml, deploy/charts/firefly/values.yaml
Closes #322
* Configuring `metrics` section of FireFly core
* Support for an optional `ServiceMonitor` object
* Tests `ServiceMonitor` install via IT test in GH actions
=> [helm] Support for Prometheus Metrics

smart_contracts/fabric/firefly-go/Dockerfile
When deploying the Fabric chaincode for FireFly to Kaleido, I need to ensure I create a Linux-compatible binary for it but I have a Mac. I did so using this Dockerfile and the following commands:
```
docker build . -t firefly-go
container_id=$(docker create firefly-go)
docker cp ${container_id}:/app/firefly.bin ./
docker rm ${container_id}
```
Using `GOOS` with the build on my Mac did not seem to work. So opening this PR to get feedback on whether this makes sense (or if I'm missing something obvious), if we need docs or additional scripting to streamline this for other folks, etc.
=> [fabric] Dockerfile for Compiling firefly-go for Linux

internal/assets/token_pool.go, internal/events/batch_pin_complete_test.go, internal/events/persist_batch.go, internal/orchestrator/data_query.go, internal/orchestrator/subscriptions.go, pkg/fftypes/datatype.go, pkg/fftypes/group.go, pkg/fftypes/message.go, pkg/fftypes/message_test.go, pkg/fftypes/namearray.go, pkg/fftypes/node.go, pkg/fftypes/node_test.go, pkg/fftypes/organization.go, pkg/fftypes/organization_test.go, pkg/fftypes/tokenpool.go, pkg/fftypes/validations.go, pkg/fftypes/validations_test.go
Currently these fields are verified only by the receiver, which can lead to
sending a bad message that is rejected on the other end.
=> Validate message topics/tag before sending

.github/workflows/go.yml
This is to fix the linter failing while checking the header copyright date for files that were not changed this year. This change pulls the full git history in the checkout stage, similar to what would happen if a user did a `git clone` on their local machine.
This PR will likely need to be merged without a passing build, due to the fact that all builds are stuck needing this change.
=> Set fetch-depth to get the full history in GitHub Actions

.github/workflows/docker_main.yml, .github/workflows/docker_release.yml, .github/workflows/go.yml, .github/workflows/helm.yml, .github/workflows/integration.yml
This is a followup to https://github.com/hyperledger/firefly/pull/377 which changes the setting in all the GitHub actions for this repo.
=> Fetch full history on all GitHub Actions

internal/database/postgres/config.go
Adding default max connection limit for PSQL to fix #380
=> [psql-maxconns] default connection limit for postgresql

internal/apiserver/server.go, internal/metrics/metrics.go, test/e2e/run.sh
The Prometheus registry panics when metrics are duplicated twice. With an `ff` bug fix in `v0.0.41`, @nguyer noticed `firefly` starts running with just the admin server, and then when it gets set to run both the admin server and the REST server without restarting the process, the admin middleware metrics would get re-registered causing a panic:
```
panic: duplicate metrics collector registration attempted
goroutine 242 [running]:
github.com/prometheus/client_golang/prometheus.(*wrappingRegisterer).MustRegister(0xc000453ad8, 0xc000453b00, 0x4, 0x4)
/go/pkg/mod/github.com/prometheus/client_golang@v1.11.0/prometheus/wrap.go:104 +0x185
gitlab.com/hfuss/mux-prometheus/pkg/middleware.(*Instrumentation).initMetrics(0xc000012a00)
/go/pkg/mod/gitlab.com/hfuss/mux-prometheus@v0.0.4/pkg/middleware/mi …
```
=> Fixing Duplicate Metrics Registration when Unsetting preInit

README.md
Adding performance testing details to README
=> Add Performance Testing Details to README

internal/tokens/fftokens/fftokens.go, internal/tokens/fftokens/fftokens_test.go, manifest.json, mocks/tokenmocks/callbacks.go
The [ERC20 token connector](https://github.com/hyperledger/firefly-tokens-erc20) for Firefly requires that `name` and `symbol` be passed to the ERC20 token factory. This PR allows for firefly to pass these fields down to the token connector.
=> [erc20-payload] pass name and symbol to CreateTokenPool()

db/migrations/postgres/000054_create_blockchainevents_table.up.sql, internal/contracts/manager.go, internal/i18n/en_translations.go, pkg/fftypes/batch.go, pkg/fftypes/batch_test.go, pkg/fftypes/contractsubscription.go, pkg/fftypes/contractsubscription_test.go, pkg/fftypes/ffi.go, pkg/fftypes/ffi_test.go, pkg/fftypes/jsonobject.go, pkg/fftypes/jsonobject_test.go, pkg/fftypes/jsonobjectarray_test.go
Fixes for #415 
The PostgreSQL driver in Go passes `Scan` a `string` rather than a `[]byte` when reading data from the database, now that we are using `TEXT` columns. However, our custom `Scan()` implementations for these types assumed `[]byte` was being returned (in various spellings of that assumption).
To support environments created before the moved away from `BYTEA` we cannot take the old `Scan()` support for `[]byte`. So we need all the objects to support either.
Through incremental e2e test-fix cycles I found the following needed updates:
1. SQL Migration copy/paste bug from SQLite to PSQL
2. `fftypes.JSONObject`
3. `fftypes.JSONObjectArray`
4. `fftypes.Batch`
5. `fftypes.FFISerializedEvent`
6. `fftypes.FFIParams`
=> PostgreSQL updates following merging of onchain-logic branch

docs/swagger/swagger.yaml, internal/apiserver/route_get_token_account_pools.go, internal/apiserver/route_get_token_accounts.go, internal/database/sqlcommon/tokenbalance_sql.go, pkg/database/plugin.go, test/e2e/restclient.go, test/e2e/tokens_test.go
Postgres has much stricter constraints on DISTINCT/GROUP BY queries - specifically,
the fields used in ORDER BY must also be part of SELECT, and therefore may need
an aggregate function applied in order to give deterministic results.
Implement ordering by "seq" or "updated", which seem like the most useful.
Resolves #416
=> Fix token account listing on Postgres

docs/swagger/swagger.yaml, internal/apiserver/route_get_token_account_pools.go, internal/apiserver/route_get_token_accounts.go, internal/database/sqlcommon/tokenbalance_sql.go, internal/i18n/en_translations.go, pkg/database/plugin.go, test/e2e/restclient.go, test/e2e/tokens_test.go
=> v0.11.x backport: Fix token account listing on Postgres

internal/events/operation_update.go, internal/events/operation_update_test.go
=> Fail transaction when token transfer operation fails

internal/database/sqlcommon/message_sql.go, internal/database/sqlcommon/message_sql_test.go, internal/events/tokens_transferred.go, internal/events/tokens_transferred_test.go, mocks/databasemocks/plugin.go, pkg/database/plugin.go
Fixes the core symptom reported in #421 
> Note that this does not implement the full change to batches described in the discussion on that issue.
> However, when that change happens, this fix will still be applicable.
=> Ready state changes require a bump to the message to re-sequence it

internal/database/sqlcommon/message_sql.go, internal/database/sqlcommon/message_sql_test.go, internal/events/tokens_transferred.go, internal/events/tokens_transferred_test.go, mocks/databasemocks/plugin.go, pkg/database/plugin.go
=> v0.11.x backport: Ready state changes require a bump to the message to re-sequence it

db/migrations/postgres/000057_add_tokentransfer_blockchainevent.down.sql, db/migrations/postgres/000057_add_tokentransfer_blockchainevent.up.sql, db/migrations/sqlite/000057_add_tokentransfer_blockchainevent.down.sql, db/migrations/sqlite/000057_add_tokentransfer_blockchainevent.up.sql, docs/swagger/swagger.yaml, internal/assets/token_transfer.go, internal/assets/token_transfer_test.go, internal/database/sqlcommon/tokentransfer_sql.go, internal/database/sqlcommon/tokentransfer_sql_test.go, internal/events/tokens_transferred_test.go, internal/tokens/fftokens/fftokens.go, internal/tokens/fftokens/fftokens_test.go, mocks/tokenmocks/plugin.go, pkg/database/plugin.go, pkg/fftypes/tokentransfer.go, pkg/tokens/plugin.go
Although transfers initiated outside of FireFly will NOT have a Transaction, it's
still useful to track Transactions for those transfers initiated by FireFly. This
is needed for tracking of async transfer requests, filtering transfers, etc.
Partially reverts 0e654d2a7b9960e3d2a4946c788f80e5052e056e
=> Restore Transaction reference on TokenTransfer

docs/swagger/swagger.yaml, internal/contracts/manager.go, internal/contracts/manager_test.go, pkg/fftypes/operation.go, pkg/fftypes/transaction.go
=> Create a Transaction and Operation for contract invoke requests

docs/swagger/swagger.yaml, internal/apiserver/route_get_blockchain_event_by_id.go, internal/apiserver/route_get_blockchain_event_by_id_test.go, internal/apiserver/route_get_blockchain_events.go, internal/apiserver/route_get_blockchain_events_test.go, internal/apiserver/routes.go, internal/contracts/manager.go, internal/contracts/manager_test.go, internal/orchestrator/data_query.go, internal/orchestrator/data_query_test.go, internal/orchestrator/orchestrator.go, mocks/contractmocks/manager.go, mocks/orchestratormocks/orchestrator.go, test/e2e/e2e_test.go, test/e2e/restclient.go
Also move the query helpers from Contract Manager to Orchestrator, as this
has become a generic construct that spans more than one manager/plugin.
=> Rename /contracts/events to /blockchainevents

test/e2e/e2e_test.go, test/e2e/stack.go
Noticed if I use the E2E tests to validate a multi-member (2+ members) network that it'd get confused about which members it was testing because the order of the members in the stack file can never be guaranteed to match the order of the orgs returned by the API of one of the nodes.
=> Fixing E2E Tests for Multi-Member Networks

pkg/wsclient/wsclient_test.go, pkg/wsclient/wstestserver.go
Fix for #445 
I wasn't able to recreate, but the test runs showed fast timeout heartbeating and connections... so I think in a slow environment a test is reconnecting the websocket after the test had finished.
Our little test websocket server would re-use the channels in that case, even though they were close
=> Avoid potential double-close of channels due to reconnects after tests complete

docs/_config.yml, docs/contributors/docs_setup.md
See https://github.com/hyperledger/firefly/pull/451
=> Use /firefly prefix on local docs dev

internal/assets/token_pool.go, internal/assets/token_transfer.go, internal/batchpin/batchpin.go, internal/broadcast/manager.go, internal/contracts/manager.go, internal/events/token_pool_created.go, internal/events/tokens_transferred_test.go, internal/privatemessaging/privatemessaging.go, internal/syncasync/sync_async_bridge_test.go, internal/txcommon/token_inputs.go, internal/txcommon/token_inputs_test.go, pkg/fftypes/operation.go, pkg/fftypes/operation_test.go
Since the transfer is only recorded upon success, all inputs must be stored
on the operation in order to support retries or accurately report failures.
Needed for #400 and #316
=> Store all token transfer inputs on operation

internal/blockchain/bifactory/factory.go, internal/database/difactory/factory.go, internal/database/difactory/plugins_cgo.go, internal/database/difactory/plugins_nocgo.go, internal/dataexchange/dxfactory/factory.go, internal/events/eifactory/factory.go, internal/identity/iifactory/factory.go, internal/publicstorage/psfactory/factory.go, internal/tokens/tifactory/factory.go
Instead of instantiating all plugins up front, instantiate them on demand.
Fixes #467
=> Make the factories act like factories

internal/definitions/definition_handler.go, internal/definitions/definition_handler_contracts.go, internal/definitions/definition_handler_contracts_test.go, internal/definitions/definition_handler_datatype.go, internal/definitions/definition_handler_datatype_test.go, internal/definitions/definition_handler_namespace.go, internal/definitions/definition_handler_namespace_test.go, internal/definitions/definition_handler_network_node.go, internal/definitions/definition_handler_network_node_test.go, internal/definitions/definition_handler_network_org.go
=> Use PreFinalize/Finalize in all definition handlers

test/e2e/e2e_test.go, test/e2e/ethereum_contract_test.go, test/e2e/fabric_contract_test.go, test/e2e/onchain_offchain_test.go, test/e2e/tokens_test.go
=> wsReader cannot rely on `testing.T` as it might extend past test scope

internal/restclient/config.go, internal/restclient/ffresty.go
Fix for #468 
For keepalive timeout there's a big disparity between Go and Node.js
- Node.js default server timeout is 5s: https://nodejs.org/api/http.html#serverkeepalivetimeout
- Go default client timeout is 90s: https://go.dev/src/net/http/transport.go
=> Set default keepalive timeout to 5s on clients for Node.js connectors

docs/swagger/swagger.yaml, internal/assets/token_pool.go, internal/assets/token_pool_test.go, internal/contracts/manager.go, internal/contracts/manager_test.go, internal/definitions/definition_handler_tokenpool.go, internal/definitions/definition_handler_tokenpool_test.go, internal/events/token_pool_created.go, internal/events/token_pool_created_test.go, internal/orchestrator/txn_status_test.go, internal/tokens/fftokens/fftokens.go, internal/tokens/fftokens/fftokens_test.go, mocks/tokenmocks/plugin.go, pkg/fftypes/operation.go, pkg/tokens/plugin.go
- Operations should all correspond to an external plugin action (only announce_pool needed a change)
- Name all operations as "plugin_action" (only contract_invoke needed a change)
- Mark operations successful after the new [synchronous forms](https://github.com/hyperledger/firefly/pull/460) of token pool creation and activation
=> Address some inconsistencies in Operation behavior

docs/swagger/swagger.yaml, internal/definitions/definition_handler_contracts.go, internal/definitions/definition_handler_contracts_test.go, internal/definitions/definition_handler_tokenpool.go, internal/definitions/definition_handler_tokenpool_test.go, internal/syncasync/sync_async_bridge.go, internal/syncasync/sync_async_bridge_test.go, pkg/fftypes/event.go
Only "message_rejected" will be emitted for rejected definition messages -
no special per-type event will be emitted.
This requires one extra lookup in syncasync to find rejected token pools,
but seems better for overall consistency.
=> Remove extra "rejected" events

db/migrations/postgres/000059_create_pins_batch_index.down.sql, db/migrations/postgres/000059_create_pins_batch_index.up.sql, db/migrations/sqlite/000059_create_pins_batch_index.down.sql, db/migrations/sqlite/000059_create_pins_batch_index.up.sql, internal/database/sqlcommon/pin_sql.go, internal/database/sqlcommon/pin_sql_test.go, internal/events/aggregator.go, internal/events/aggregator_batch_state.go, internal/events/aggregator_batch_state_test.go, internal/events/aggregator_test.go, internal/events/webhooks/webhooks.go, mocks/databasemocks/plugin.go, pkg/database/plugin.go, test/e2e/e2e_test.go, test/e2e/onchain_offchain_test.go, test/e2e/restclient.go, test/e2e/tokens_test.go
Fix for #481 
We were failing to process multiple private messages on the same topic, within a single batch of pins that are read by the aggregator. This was a side-effect of the #462 changes - because the logic that evaluates the `NextPin` state on each message no longer had up-to-date information to read from the database.
The core fix implemented for that, was to move to in-memory processing for all state that can change during processing of a page of pins in the aggregator. So the first time we access the state on a context (context is a particular `topic`, scoped to a group if it's a private context), we read the data we need in memory and from that point on we update it in memory until the `Finalize` phase is called at the end. At that point everything is flushed.
Fixing this turned …
=> Update aggregator batch processing to maintain in-memory pin state until OnFinalize

internal/blockchain/fabric/fabric.go
Signed-off-by: Jim Zhang <jim.zhang@kaleido.io>
=> Fix fabric event timestamp parsing

Dockerfile, Makefile, docker_build.sh, manifest.json, manifestgen.sh, smart_contracts/ethereum/solidity_firefly/package.json, smart_contracts/ethereum/solidity_firefly/truffle-config.js, test/e2e/run.sh
Resolves https://github.com/hyperledger/firefly/issues/469
=> Fix Docker build on ARM

internal/apiserver/http_server_test.go, pkg/wsclient/wsclient.go
Fix for #485 with a bonus fix for this timing issue I'm seeing intermittently since upgrading my laptop.
```
time="2022-02-07T13:21:00-05:00" level=info msg="API server context cancelled - shutting down"
time="2022-02-07T13:21:00-05:00" level=info msg="API server complete"
--- FAIL: TestTLSServerSelfSignedWithClientAuth (0.13s)
http_server_test.go:197: 
Error Trace:    http_server_test.go:197
Error:          Received unexpected error:
context deadline exceeded
Test:           TestTLSServerSelfSignedWithClientAuth
```
=> Fix possibility for nil access in sendloop

test/e2e/onchain_offchain_test.go, test/e2e/restclient_test.go
Fix for #487 
Note rename of `restclient.go` to `restclient_test.go` is to allow it to share `testState`
=> Fix group to be constant throughout test

internal/batch/batch_manager.go, internal/batch/batch_manager_test.go
Fix for #493 
Observed reviewing the logs for #493 that the messages were never being picked up by the batch processor, and the perf tool is submitting them in a highly parallel way. My analysis is that with PSQL as used in this test (or any production ready database) parallel writing of messages to the DB could result in the commit order of the transactions, being mismatched with the sequence allocation to the rows. 
The code in the batch manager did not handle this - it would simply do a shoulder tap to re-read from the DB when a message was created, but not check if that message had appeared behind the offset and it needed to do a rewind.
This code change implements a simple rewind (like we have for the event aggregator).
Note this means that in the case of parallel REST API submission …
=> Rewind when messages appear behind offset

db/migrations/postgres/000060_remove_operation_backendid.down.sql, db/migrations/postgres/000060_remove_operation_backendid.up.sql, db/migrations/sqlite/000060_remove_operation_backendid.down.sql, db/migrations/sqlite/000060_remove_operation_backendid.up.sql, docs/swagger/swagger.yaml, internal/assets/token_pool.go, internal/assets/token_transfer.go, internal/batchpin/batchpin.go, internal/broadcast/manager.go, internal/broadcast/manager_test.go, internal/contracts/manager.go, internal/database/sqlcommon/operation_sql.go, internal/database/sqlcommon/operation_sql_test.go, internal/dataexchange/dxhttps/dxhttps.go, internal/dataexchange/dxhttps/dxhttps_test.go, internal/events/dx_callbacks.go, internal/events/dx_callbacks_test.go, internal/orchestrator/bound_callbacks_test.go, internal/privatemessaging/message_test.go, internal/privatemessaging/privatemessaging.go, internal/privatemessaging/privatemessaging_test.go, manifest.json, mocks/dataexchangemocks/plugin.go, pkg/database/plugin.go, pkg/dataexchange/plugin.go, pkg/fftypes/operation.go, pkg/fftypes/operation_test.go, pkg/fftypes/transport_wrapper.go
Follow the convention of all other plugins by passing a request ID into the
connector, rather than reading one from the connector response. This will be
enforced as a requirement for future connectors, so backend_id is removed from
the operations table.
Depends on https://github.com/hyperledger/firefly-dataexchange-https/pull/54
=> Pass requestId to DX and remove backend_id from Operation

internal/dataexchange/dxfactory/factory.go, internal/dataexchange/ffdx/config.go, internal/dataexchange/ffdx/ffdx.go, internal/dataexchange/ffdx/ffdx_test.go, internal/orchestrator/orchestrator.go, internal/orchestrator/orchestrator_test.go
Resolves #259
Open to other names here, but we landed on "fftokens" for the tokens plugin, so this seemed reasonable.
The name just needs to be globally unique in FireFly across all plugins, and identifiable as a data exchange plugin
vs. some other type of plugin.
=> Rename data exchange plugin to "ffdx"

internal/assets/token_pool.go, internal/assets/token_pool_test.go, internal/assets/token_transfer.go, internal/assets/token_transfer_test.go, internal/contracts/manager.go, internal/contracts/manager_test.go, internal/database/sqlcommon/operation_sql.go, internal/database/sqlcommon/operation_sql_test.go, internal/events/dx_callbacks.go, internal/events/dx_callbacks_test.go, internal/events/operation_update.go, internal/events/operation_update_test.go, internal/events/token_pool_created.go, internal/events/token_pool_created_test.go, internal/txcommon/txcommon.go, internal/txcommon/txcommon_test.go, mocks/blockchainmocks/plugin.go, mocks/databasemocks/plugin.go, mocks/txcommonmocks/helper.go, pkg/blockchain/plugin.go, pkg/database/plugin.go, pkg/fftypes/operation.go, pkg/fftypes/operation_test.go, pkg/tokens/plugin.go
Ensure the operations for tokens and custom contracts behave as expected in success/failure scenarios.
=> Misc fixes for operations

internal/batch/batch_processor.go, internal/database/sqlcommon/event_sql.go, internal/database/sqlcommon/sqlcommon.go
This is to avoid the A->B, B->A deadlock due to differently ordered database operations with the new table lock, seen under a high concurrency performance test in https://github.com/hyperledger/firefly/issues/493#issuecomment-1036607936
=> Move insert of events to a special pre-commit phase of the DB transaction

internal/dataexchange/ffdx/ffdx.go, internal/dataexchange/ffdx/ffdx_test.go
... details in the comments of the change
=> Flatten the DXInfo back to the orginal payload on the ffdx API to connectors

internal/database/postgres/postgres.go, internal/database/postgres/postgres_test.go, internal/database/sqlcommon/group_sql.go, internal/database/sqlcommon/group_sql_test.go, internal/database/sqlcommon/provider.go, internal/database/sqlcommon/provider_mock_test.go, internal/database/sqlcommon/provider_sqlitego_test.go, internal/database/sqlcommon/sqlcommon.go, internal/database/sqlite3/sqlite3.go, internal/database/sqlite3/sqlite3_test.go, internal/privatemessaging/groupmanager.go, internal/privatemessaging/groupmanager_test.go, internal/privatemessaging/recipients_test.go, mocks/databasemocks/plugin.go, pkg/database/plugin.go
Proposed fix for #512 
By implementing the `UpsertOptimization` pattern for Groups, it lets us state `UpsertOptimizationNew` everywhere we're currently just trying to do a query-then-insert approach. `UpsertOptimizationNew` results in an attempt-insert, then attempt-update approach - which should handle+swallow a duplicate key exception (rather than rolling back the TX).
=> Implement and use UpsertOptimization for groups

Dockerfile
This would allow us remove the bits in the [helm chart](https://github.com/hyperledger/firefly-helm-charts/blob/main/charts/firefly/scripts/ff-register-contracts.sh#L21) that download `apk` packages at runtime. This is a best practice for Docker images and would allow enterprises using the chart / images to use them within their networks where they do not allow for public internet access.
Obviously the chart could simply use different images (however for migrations we take advantage of the fact that the migration are bundled into the firefly image), however I wanted to get the community's feedback on taking the hit in the image size being slightly larger for the sake of operational simplicity.
=> Provide Migration / Registration / Debugging Utilities in Docker Image

Dockerfile
Follow up to #521, realized the chart scripts also were downloading [`go-migrate`](https://github.com/hyperledger/firefly-helm-charts/blob/main/charts/firefly/scripts/ff-db-migrations.sh#L55-L57) as well so this adds that.
Definitely further re-enforces @peterbroadhurst's comment about a separate `utiltity` tag or image for firefly in the future.
=> go-migrate in Dockerfile

.github/workflows/docker_main.yml, .github/workflows/docker_release.yml
Fixes #527 
My theory (can't prove without actions running) is that the `'` single quotes is just passing the special `${GITHUB_REF##*/}` bash syntax into `make` - which doesn't understand all that fancyness, and is just treating it as an empty variable
=> Use bash for variable expansion prior to make

.dockerignore
If you currently try and do `make` in Docker, including the unit tests, it fails because the `.git` history is not there so the linter doesn't know when the last change was to apply the copyright building correctly:
```
[0minternal/log/log.go:1:17: Expected:2022, Actual: 2021 Kaleido, Inc. (goheader)
// Copyright © 2021 Kaleido, Inc.
^
internal/i18n/errors.go:1:17: Expected:2022, Actual: 2021 Kaleido, Inc. (goheader)
// Copyright © 2021 Kaleido, Inc.
^
internal/i18n/messages.go:1:17: Expected:2022, Actual: 2021 Kaleido, Inc. (goheader)
// Copyright © 2021 Kaleido, Inc.
^
[91mlevel=info msg="File cache stats: 325 entries of total size 1.2MiB"
level=info msg="Memory: 826 samples, avg is 225.0MB, max is 276.1MB"
level=info msg="Execution took 1m22.599796017s"
[0m[91mmake: *** …
```
=> Allow building in docker by removing .git from .dockerignore

internal/blockchain/ethereum/ethereum.go, internal/blockchain/ethereum/ethereum_test.go
=> Add additional backwards compatibility check on ethereum instance path

docs/swagger/swagger.yaml, internal/apiserver/route_post_contract_api_invoke.go, internal/apiserver/route_post_contract_interface_invoke.go, internal/apiserver/route_post_contract_invoke.go, internal/blockchain/ethereum/ethereum.go, internal/blockchain/ethereum/ethereum_test.go, internal/blockchain/fabric/fabric.go, internal/blockchain/fabric/fabric_test.go, internal/contracts/manager.go, internal/contracts/manager_test.go, mocks/blockchainmocks/plugin.go, pkg/blockchain/plugin.go, pkg/fftypes/contracts.go
Instead of proxying the response from ethconnect/fabconnect, successful
"InvokeContract" calls can return a predictable response body constructed
by the Contract Manager.
The request ID (which is actually the FireFly operation ID) was the only
interesting thing returned in the first place, so starting with just that
in the new response body.
=> Build a predictable response body for async "InvokeContract" calls

docs/swagger/swagger.yaml, internal/apiserver/route_post_contract_interface_generate.go, internal/apiserver/route_post_contract_interface_generate_test.go, internal/apiserver/routes.go, internal/blockchain/ethereum/ethereum.go, internal/blockchain/ethereum/ethereum_test.go, internal/blockchain/fabric/fabric.go, internal/blockchain/fabric/fabric_test.go, internal/contracts/manager.go, internal/contracts/manager_test.go, internal/i18n/en_translations.go, mocks/blockchainmocks/plugin.go, mocks/contractmocks/manager.go, pkg/blockchain/plugin.go, pkg/fftypes/ffi.go, test/data/assetcreator/chaincode/smartcontract.go
This PR adds an endpoint to automatically generate an FFI. The implementation is handled by the blockchain plugin. Right now, only the Ethereum plugin implements this functionality, but other blockchain plugins in the future could as well, if they have their own DSL to describe a smart contract.
Resolves https://github.com/hyperledger/firefly/issues/397
=> Add endpoint to automatically generate an FFI

internal/dataexchange/ffdx/ffdx.go, internal/dataexchange/ffdx/ffdx_test.go, internal/events/dx_callbacks.go, internal/events/dx_callbacks_test.go, internal/i18n/en_translations.go, internal/privatemessaging/privatemessaging.go, pkg/fftypes/transport_wrapper.go
Signed-off-by: Gabriel Indik <gabriel.indik@kaleido.io>
=> Updates to DX

internal/blockchain/fabric/fabric.go, internal/blockchain/fabric/fabric_test.go, test/data/assetcreator/chaincode/smartcontract.go, test/e2e/fabric_contract_test.go
This PR also removes query parameters on `POST` requests to Fabconnect in favor of always using the request body and a well defined `payloadSchema`
=> Add query support for Fabric

internal/apiserver/route_post_new_contract_api.go, internal/apiserver/route_post_new_contract_api_test.go, internal/apiserver/route_put_contract_api.go, internal/apiserver/route_put_contract_api_test.go, internal/contracts/manager.go, internal/contracts/manager_test.go, mocks/contractmocks/manager.go
Resolves https://github.com/hyperledger/firefly/issues/539
=> Fix empty swagger URLs on contract API creation

internal/database/sqlcommon/data_sql.go, internal/database/sqlcommon/message_sql.go
Fixes #550
The comment in https://github.com/hyperledger/firefly/pull/513#issuecomment-1036844541 held true - we need to roll the `requestConflictEmptyResult` tweak out to the other optimization cases.
=> Roll requestConflictEmptyResult from Group to Data and Message too

internal/blockchain/ethereum/ethereum.go, internal/blockchain/ethereum/eventstream.go, internal/contracts/manager.go
=> Explicitly name all subscriptions

docs/contributors/contributors.md, docs/gettingstarted/events.md, docs/swagger/swagger.yaml, internal/apiserver/route_get_events.go, internal/apiserver/route_get_events_test.go, internal/orchestrator/data_query.go, internal/orchestrator/data_query_test.go, internal/orchestrator/orchestrator.go, internal/orchestrator/orchestrator_test.go, mocks/orchestratormocks/orchestrator.go
`fetchreferences` will add the referred object to the GET /events response
closes #580
=> add `fetchreferences` param to events api

internal/blockchain/ethereum/ethereum_test.go, internal/blockchain/ethereum/eventstream.go, internal/blockchain/fabric/eventstream.go, internal/blockchain/fabric/fabric_test.go
Signed-off-by: jebonfig <joe.bonfiglio@kaleido.io>
=> Scope subscription check to the appropriate stream ID

internal/batch/batch_manager.go, internal/batch/batch_manager_test.go, internal/broadcast/definition.go, internal/broadcast/manager.go, internal/broadcast/manager_test.go, internal/broadcast/message.go, internal/broadcast/message_test.go, internal/broadcast/operations.go, internal/data/data_manager.go, internal/data/data_manager_test.go, internal/data/message_writer.go, internal/data/message_writer_test.go, internal/events/aggregator.go, internal/events/aggregator_test.go, internal/privatemessaging/message.go, internal/privatemessaging/message_test.go, internal/restclient/ffresty.go, mocks/datamocks/manager.go
Resolves #595 
- No longer set `CRORequirePublicBlobRefs` when assembling the messages prior to dispatching a batch (timing issue with this seen in #595)
- Move upload of blobs from API thread, to the batch dispatch thread
- Set `CRORequirePublicBlobRefs` when aggregating pins for broadcast messages
=> Move blob publish to broadcast batch dispatch, ensure public refs on inbound

internal/database/sqlcommon/chart_sql.go, internal/database/sqlcommon/chart_sql_test.go, pkg/database/plugin.go
Adding support for blockchain event charting, so that the new UI can include blockchain event histograms.
This was a bigger change than expected since blockchain events have no `type` field, and are also timestamped by a `timestamp` field rather than a `created` field. This resulted in a `getHistogramNoTypes()` method and a `getHistogramWithTypes()` method.
=> [blockchainevents-charts] support for blockchain event charting

docs/swagger/swagger.yaml, internal/apiserver/route_get_net_node.go, internal/apiserver/route_get_net_node_test.go, internal/apiserver/route_get_net_org.go, internal/apiserver/route_get_net_org_test.go, internal/networkmap/data_query.go, internal/networkmap/data_query_test.go, internal/networkmap/manager.go, mocks/networkmapmocks/manager.go
=> Change node/org lookups to support name or ID

.github/workflows/integration.yml, test/e2e/run.sh
This does not affect the PR test runs - only the daily integration test job - or if a `RESTART` environment variable is set to `true`.
Resolves https://github.com/hyperledger/firefly/issues/566
=> Restart stack and re-run E2E tests in daily integration job

go.mod, go.sum, internal/blockchain/ethereum/config.go, internal/config/config.go, internal/dataexchange/dxfactory/factory.go, internal/orchestrator/orchestrator.go, internal/orchestrator/orchestrator_test.go
Signed-off-by: Gabriel Indik <gabriel.indik@kaleido.io>
=> Switch from https to ffdx

internal/database/sqlcommon/namespace_sql.go, internal/database/sqlcommon/namespace_sql_test.go, internal/txcommon/event_enrich.go, internal/txcommon/event_enrich_test.go, mocks/databasemocks/plugin.go, pkg/database/plugin.go, pkg/fftypes/event.go
`GET /events?fetchreferences` now returns enriched events for all event types:
```go
type EnrichedEvent struct {
Event
BlockchainEvent   *BlockchainEvent `json:"blockchainevent,omitempty"`
ContractAPI       *ContractAPI     `json:"contractAPI,omitempty"`
ContractInterface *FFI             `json:"contractInterface,omitempty"`
Datatype          *Datatype        `json:"datatype,omitempty"`
Identity          *Identity        `json:"identity,omitempty"`
Message           *Message         `json:"message,omitempty"`
NamespaceDetails  *Namespace       `json:"namespaceDetails,omitempty"`
TokenApproval     *TokenApproval   `json:"tokenApproval,omitempty"`
TokenPool         *TokenPool       `json:"tokenPool,omitempty"`
Transaction       *Transaction     `json:"transaction,omitempty"`
TokenTransfer …
```
=> [fetchreferences2] Adding event enrichment for all event types

cmd/firefly.go, cmd/firefly_test.go
Now that we are using more standard deployment of Ethereum contracts in the FireFly CLI, where a unique Eth address is generated each time, we need to set that configuration.
Rather than having configuration like this that's only in the DB, this PR proposes we re-read the configuration after the reset to pick up patched YAML configuration containing the instance address.
We still need to use the `preInit` trick in the CLI to let it start in a zombie mode so Docker compose is happy, while we're using EthConnect to deploy the contract, but the only thing we use the DB config patch for is to unset this flag (which is true already today).
=> Re-read configuration on restart of orchestrator

db/migrations/postgres/000011_create_events_table.up.sql, db/migrations/sqlite/000011_create_events_table.up.sql
Saw the below error in a long-run test, where an attempt to insert an event resulted in no rows being added in PSQL with `ON CONFLICT DO NOTHING RETURNING seq`. I found there's an index that is set to `UNIQUE` on the `created` timestamp, and while a clash there is unlikely it's definitely possible.
```
{"log":"[2022-03-27T20:45:44.100Z]  WARN node_0: SQL! transaction rollback dbtx=WLXd2cMS httpreq=GJpFajph req=w6nJtbSg\n","stream":"stderr","time":"2022-03-27T20:45:44.102693254Z"}
{"log":"[2022-03-27T20:45:44.102Z]  INFO node_0: \u003c-- POST /api/v1/namespaces/default/contracts/invoke [500] (19.62ms): FF10116: Database insert failed: FF10375: Failed to retrieve sequence for insert row 1 (could mean duplicate insert) httpreq=GJpFajph …
```
=> Created timestamp index on events shouldn't be unique

db/migrations/postgres/000076_add_tokentransfer_message_index.down.sql, db/migrations/postgres/000076_add_tokentransfer_message_index.up.sql, db/migrations/sqlite/000076_add_tokentransfer_message_index.down.sql, db/migrations/sqlite/000076_add_tokentransfer_message_index.up.sql
Found a very expensive DB query for this message - which is a transfer broadcast:
```
{"log":"[2022-03-28T18:28:15.165Z] DEBUG node_0: Aggregating pin 0000628232 batch=30699806-5fc3-441e-b05f-8d2c9d28fc5e msg=7e41907b-5d34-41c0-87a5-61ccafaf9885 pinIndex=1 msgBaseIndex=1 hash=37a8eec1ce19687d132fe29051dca629d164e2c4958ba141d5f4133a33f0688f masked=false dbtx=Z5gQrpfP role=aggregator\n","stream":"stderr","time":"2022-03-28T18:28:15.16525934Z"}
{"log":"[2022-03-28T18:28:15.165Z] DEBUG node_0: Cache hit for message 7e41907b-5d34-41c0-87a5-61ccafaf9885 dbtx=Z5gQrpfP role=aggregator\n","stream":"stderr","time":"2022-03-28T18:28:15.16527267Z"}
{"log":"[2022-03-28T18:28:15.165Z] DEBUG node_0: Attempt dispatch msg=7e41907b-5d34-41c0-87a5-61ccafaf9885 …
```
=> Add index on message_id for token transfers

internal/batch/batch_processor.go, internal/data/data_manager.go, internal/data/data_manager_test.go, internal/events/aggregator_batch_state.go, internal/events/aggregator_batch_state_test.go, internal/events/aggregator_test.go, internal/shareddownload/download_manager_test.go, mocks/datamocks/manager.go
Noticed in the UI that confirmed messages on the Timeline view are showing as `Pending` - which is because they are using the cache rather than an explicit query against the DB. This PR updates the cache when messages are batched, or confirmed.
=> Update our cache for event enrichment on message confirm

db/migrations/postgres/000077_add_transactions_id_index.up.sql, db/migrations/sqlite/000005_create_transactions_table.up.sql, db/migrations/sqlite/000077_add_transactions_id_index.up.sql, internal/events/dx_callbacks.go, internal/events/ss_callbacks.go
- Fixes migration
- Fixes a log entry that was at the wrong level
=> Fix IF EXISTS check on transactions_id INDEX migration

internal/privatemessaging/privatemessaging.go, internal/privatemessaging/privatemessaging_test.go
- Use a single database transaction to write all the `pending` `operations` needed to dispatch a private messaging batch
- Then initiate all the HTTP calls to DX separately - noting these should be *pending* until the asynchronous callback comes
=> Use a single commit to generate all batch ops, before initiating the HTTP calls

db/migrations/postgres/000078_add_nonce_author.down.sql, db/migrations/postgres/000078_add_nonce_author.up.sql, db/migrations/sqlite/000078_add_nonce_author.down.sql, db/migrations/sqlite/000078_add_nonce_author.up.sql, internal/batch/batch_manager_test.go, internal/batch/batch_processor.go, internal/batch/batch_processor_test.go, internal/database/sqlcommon/nonce_sql.go, internal/database/sqlcommon/nonce_sql_test.go, mocks/databasemocks/plugin.go, pkg/database/plugin.go, pkg/fftypes/nonce.go
This PR addresses two problems:
1) Currently when we are flushing a batch, we perform a DB read+update individually. This is very inefficient when you have a large number of messages for the same topic+group combination in the same batch. Instead we can keep a track in memory of the nonce increments, and flush them one time at the end of the dispatch.
2) I found while investigating (1) that we were not including the `author` of the message in the calculation of which Nonce we assigned from the DB. This is a bug. e.g. if you sent a message on `topicA` in a group with both `bob` and `sally` using author `bob`, then sent another message _from the same node_ as `sally` on the same `topicA` - then `sally` would get the wrong nonce.
As per the comments, some consideration has been made to …
=> Assign nonces more efficiently, with minimal DB ops

internal/config/config.go, internal/database/sqlcommon/chart_sql.go, internal/database/sqlcommon/chart_sql_test.go
Previously, histogram buckets were created with a `CASE` query. This lead to performance issues when a large amount of data was queried from the database. 
This new method sets a max amount of rows to be queried in each bucket, with a default of 100 rows. 
The data structure and expected response is unchanged.
=> [charts-config] chart buckets are now capped at a configurable max

internal/assets/token_approval.go, internal/database/sqlcommon/tokenapproval_sql.go, internal/database/sqlcommon/tokenapproval_sql_test.go, internal/events/tokens_approved.go, internal/events/tokens_approved_test.go, internal/syncasync/sync_async_bridge.go, internal/syncasync/sync_async_bridge_test.go, internal/txcommon/event_enrich.go, internal/txcommon/event_enrich_test.go, mocks/databasemocks/plugin.go, pkg/database/plugin.go, test/e2e/e2e_test.go, test/e2e/tokens_test.go
- Ensure existing approvals are not being overwritten
- Remove localID from async/sync POST response
- Commented out approvals from synchronous tokens e2e test due to https://github.com/hyperledger/firefly/issues/661
=> Proper handling of token approval events

docs/swagger/swagger.yaml, internal/database/sqlcommon/chart_sql.go, internal/database/sqlcommon/chart_sql_test.go, pkg/fftypes/charthistogram.go
New Response:
```json
[
{
"count": "0",
"isCapped": false,
"timestamp": "2022-04-06T23:21:00Z",
"types": []
},
{
"count": "100",
"isCapped": true,
"timestamp": "2022-04-07T00:57:00Z",
"types": [
{
"count": "1",
"type": "token_pool_confirmed"
},
{
"count": "37",
"type": "message_confirmed"
},
{
"count": "12",
"type": "token_transfer_confirmed"
},
{
"count": "25",
"type": "transaction_submitted"
},
{
"count": "25",
"type": "blockchain_event_received"
}
]
}
]
```
=> [charts-isCapped] adding isCapped key to charts response

docs/swagger/swagger.yaml, internal/coremsgs/en_struct_descriptions.go, internal/events/event_manager.go, internal/events/event_manager_test.go, internal/orchestrator/status.go, internal/orchestrator/status_test.go, mocks/eventmocks/event_manager.go, pkg/fftypes/node_status.go
`GET /api/v1/status` now returns a `plugin` key:
```json
{
"node": {...},
"org": {...},
"defaults": {...},
"plugins": {
"blockchain": [
{
"pluginType": "ethereum"
}
],
"database": [
{
"pluginType": "sqlite3"
}
],
"dataExchange": [
{
"pluginType": "ffdx"
}
],
"events": [
{
"pluginType": "system"
},
{
"pluginType": "websockets"
},
{
"pluginType": "webhooks"
}
],
"identity": [
{
"pluginType": "onchain"
}
],
"sharedStorage": [
{
"pluginType": "ipfs"
}
],
"tokens": [
{
"name": "erc1155",
"pluginType": "fftokens"
}
]
}
}
```
=> Status plugins

internal/database/sqlcommon/contractapis_sql.go, internal/database/sqlcommon/contractapis_sql_test.go, internal/definitions/definition_handler_contracts.go, internal/definitions/definition_handler_contracts_test.go
Fixes #703
More work can be done to reject upfront for a better user experience, but this fixes the important bug that blocks event processing.
=> Reject Contract API updates with an ID mismatch

.github/workflows/go.yml
When trying to investigate https://github.com/hyperledger/firefly/runs/6001824099?check_suite_focus=true I found that I didn't have the container logs.
Looks like it's due to a clash in the names between the token tests
=> Add token provider to container logs name to make it unique

internal/assets/operations.go, internal/assets/operations_test.go, internal/batchpin/operations.go, internal/batchpin/operations_test.go, internal/broadcast/operations.go, internal/broadcast/operations_test.go, internal/contracts/operations.go, internal/contracts/operations_test.go, internal/operations/manager.go, internal/operations/manager_test.go, internal/operations/operation_updater.go, internal/operations/operation_updater_test.go, internal/privatemessaging/operations.go, internal/privatemessaging/operations_test.go, internal/shareddownload/operations.go, internal/shareddownload/operations_test.go
Feels like these should be farmed out instead of Operations Manager having knowledge of the various specific operation types.
=> Move "special" operation update handling out of Operations Manager

test/e2e/run.sh
We recently merged a change in how blockchain accounts are created for the E2E tests. This worked fine for a normal run. The nightly integration test also stops all the services, starts them up again, and re-runs all the tests. This meant that there weren't enough "extra" test blockchain accounts allocated for the second test run after the restart. This PR fixes that.
=> Fix account creation for nightly integration runs

docs/swagger/swagger.yaml, internal/oapispec/openapi3.go
Type is unknown, as it may be any valid JSON.
See https://github.com/hyperledger/firefly-sdk-nodejs/issues/18
=> Use blank type for JSONAny in OpenAPI

internal/blockchain/ethereum/ethereum.go, internal/blockchain/ethereum/ethereum_test.go, internal/blockchain/fabric/fabric.go, internal/blockchain/fabric/fabric_test.go, internal/tokens/fftokens/fftokens.go, internal/tokens/fftokens/fftokens_test.go
```
Parse a JSON error of the form:
{"error": "Bad Request", "message": "Field 'x' is required"}
into a message of the form:
"Bad Request: Field 'x' is required"
```
See https://github.com/hyperledger/firefly/issues/753
=> Format JSON errors from connectors

internal/txcommon/event_enrich.go, internal/txcommon/event_enrich_test.go, pkg/fftypes/event.go
- TokenPoolOpFailed
- BlockchainInvokeOpSucceeded
- BlockchainInvokeOpFailed
closes #736
=> add additional event enrichment

docs/swagger/swagger.yaml, internal/apiserver/route_get_token_connectors.go, internal/assets/manager.go, internal/assets/manager_test.go, internal/assets/token_approval.go, internal/assets/token_approval_test.go, internal/assets/token_pool.go, internal/assets/token_pool_test.go, internal/assets/token_transfer.go, internal/assets/token_transfer_test.go, mocks/assetmocks/manager.go, pkg/fftypes/tokenapproval.go, pkg/fftypes/tokentransfer.go
This should always be inferred from the token pool.
Fixes #768
=> Omit "connector" from token transfer/approval inputs

CONTRIBUTING.md, README.md
I deleted the previous branch when i noticed my git credentials had not been updated in my signed commits.
This PR still addresses the two links.
=> Fix links in documentation

cmd/firefly.go, go.sum
CORS defaults were not being applied any more, after #791 moved the initialization to be alongside all the rest of the HTTP server config.
We were initializing those config prefixes, before we were calling `coreconfig.Reset()`
=> Do not init apiserver config, until after config reset

cmd/firefly.go, docs/config_docs_generate_test.go, docs/config_docs_test.go, docs/reference/config.md, internal/coreconfig/coreconfig.go, internal/coremsgs/en_config_descriptions.go, internal/orchestrator/orchestrator.go, internal/orchestrator/orchestrator_test.go
Makes the allowed subkeys clearer, especially if more are to be added in the future.
=> Define config schema for namespaces.predefined

test/data/config/firefly.core.yaml
Saw a build failure in https://github.com/hyperledger/firefly/runs/6530517574?check_suite_focus=true
```
Error: FF00151: Unable to start listener on 127.0.0.1:6000: %!s(MISSING): listen tcp 127.0.0.1:6000: bind: address already in use
```
We have config to get a dynamically assigned port for these tests for `debug` and `http`, but not for `metrics`
=> Possible to see clash on port 6000 for metrics server

docs/reference/types/_includes/event_description.md
=> Fix link to events reference

docs/reference/types/_includes/blockchainevent_description.md, docs/reference/types/_includes/event_description.md, docs/reference/types/_includes/identity_description.md, docs/reference/types/_includes/message_description.md, docs/reference/types/_includes/operation_description.md, docs/reference/types/_includes/subscription_description.md, docs/reference/types/_includes/transaction_description.md, docs/reference/types/_includes/wsack_description.md
=> Fix relative links in reference descriptions docs

.github/workflows/docs.yml, Makefile, internal/blockchain/fabric/fabric.go
The fabconnect default for `/transactions` is synchronous. The fabric plugin currently expects async responses, so adding the `x-firefly-sync` header.
=> default fabconnect calls to async

internal/broadcast/message.go, internal/privatemessaging/message.go
FireFly now sets the message type for any broadcast or private messages
sent via the API.
=> set message header type for broadcast/private

docs/config_docs_generate_test.go, docs/reference/config.md, docs/swagger/swagger.yaml, go.sum, internal/blockchain/ethereum/ethereum.go, internal/blockchain/ethereum/ethereum_test.go, internal/blockchain/fabric/fabric.go, internal/blockchain/fabric/fabric_test.go, internal/contracts/manager.go, internal/contracts/manager_test.go, internal/contracts/operations.go, internal/contracts/operations_test.go, internal/coremsgs/en_error_messages.go, internal/coremsgs/en_struct_descriptions.go, internal/oapiffi/ffi2swagger_test.go, mocks/blockchainmocks/plugin.go, pkg/blockchain/plugin.go, pkg/core/contracts.go
This PR adds the ability to pass additional options through to blockchain connectors. This is useful for controlling other parameters when submitting a blockchain transaction besides the specific arguments that a smart contract function takes. For example, this can now be used to set a custom gas price
Anywhere that a smart contract can be invoked or queried a new `options` JSON object (treated as a `map[string]interface{}` in Go) can be optionally specified. Any fields in this structure will be included in the request to the blockchain connector.
Overriding existing fields in the request is **not** allowed. For example, if using Ethconnect, the following request body would be rejected because `headers` is a field that FireFly itself needs to set:
```json
{
"input": {
"newValue": "x"
}, …
```
=> Allow extra options to pass through to blockchain connectors

internal/blockchain/ethereum/ethereum.go, internal/blockchain/ethereum/ethereum_test.go, internal/blockchain/fabric/fabric.go, internal/blockchain/fabric/fabric_test.go, internal/events/network_action.go, internal/events/network_action_test.go, internal/identity/identitymanager.go, internal/identity/identitymanager_test.go, internal/metrics/metrics.go, internal/orchestrator/orchestrator.go, internal/orchestrator/orchestrator_test.go, mocks/blockchainmocks/plugin.go, pkg/blockchain/plugin.go
Network version is loaded during blockchain plugin init, instead of lazily. This is (soon) going to be needed at manager initialization time, so might as well load it once upfront.
Since we currently have a single blockchain plugin that services all namespaces, any termination/migration event is recorded against ALL namespaces (rather than arbitrarily recording it against ff_system only).
=> Enhancements to migration/network version behavior

db/migrations/postgres/000092_add_pin_namespace.down.sql, db/migrations/postgres/000092_add_pin_namespace.up.sql, db/migrations/sqlite/000092_add_pin_namespace.down.sql, db/migrations/sqlite/000092_add_pin_namespace.up.sql, docs/swagger/swagger.yaml, internal/apiserver/route_get_pins.go, internal/apiserver/route_get_pins_test.go, internal/apiserver/route_get_status_pins.go, internal/apiserver/route_get_status_pins_test.go, internal/apiserver/routes.go, internal/coremsgs/en_api_translations.go, internal/coremsgs/en_struct_descriptions.go, internal/database/sqlcommon/pin_sql.go, internal/database/sqlcommon/pin_sql_test.go, internal/events/batch_pin_complete.go, internal/orchestrator/data_query.go, internal/orchestrator/data_query_test.go, internal/orchestrator/orchestrator.go, internal/orchestrator/persistence_events.go, internal/orchestrator/persistence_events_test.go, mocks/databasemocks/callbacks.go, mocks/databasemocks/plugin.go, mocks/orchestratormocks/orchestrator.go, pkg/core/pin.go, pkg/database/plugin.go
Existing pins will all be categorized against "ff_system", just so the field has a non-null value.
=> Add namespace to pins

docs/swagger/swagger.yaml, pkg/core/batch.go
This field is not used by any code.
There was a vision that storing the `payloadRef` on broadcast batches for reference, but this was never implementing. Meaning this field is cruft.
Currently the right way to find the payload reference, is to look at the upload/download operations for the batch.
=> Remove redundant payloadRef field on Batch Pin

internal/dataexchange/ffdx/dxevent.go, internal/dataexchange/ffdx/ffdx_test.go, mocks/dataexchangemocks/dx_event.go, pkg/dataexchange/plugin.go, test/e2e/e2e_test.go, test/e2e/ethereum_contract_test.go, test/e2e/fabric_contract_test.go, test/e2e/identity_test.go, test/e2e/onchain_offchain_test.go, test/e2e/restclient_test.go, test/e2e/tokens_test.go
Fixes #871 
Also enhance all E2E test suites to check for stuck operations, as this seems to be a recurring theme that slips through the cracks.
=> Resolve DX operations via requestID (not event ID)

internal/coreconfig/coreconfig.go, internal/orchestrator/orchestrator.go
This default value will be totally removed in v1.1+ due to #878. Deprecating it on the v1.0.x train will give a cleaner migration path forward.
=> Deprecate default value for "ffdx"

docs/reference/types/tokentransfer.md, docs/swagger/swagger.yaml, internal/coremsgs/en_struct_descriptions.go, internal/tokens/fftokens/fftokens.go, internal/tokens/fftokens/fftokens_test.go, pkg/core/tokentransfer.go
These changes also include added an optional `config` parameter, that is passed to directly to the token connectors without validation.
=> surface URI as parameter for token mint

docs/reference/types/tokentransfer.md, docs/swagger/swagger.yaml, internal/coremsgs/en_struct_descriptions.go, internal/tokens/fftokens/fftokens.go, internal/tokens/fftokens/fftokens_test.go, pkg/fftypes/tokentransfer.go
back port of https://github.com/hyperledger/firefly/pull/879
=> back port of custom URI support for non-fungible tokens

test/e2e/run.sh
Disable parallelization and reduce test timeout to 1m.
This re-enables streaming logs during E2E runs (which is disabled by default when running suites in parallel). No real impact since our test jobs are already divided such that they run 1 suite per job.
=> Fix logs from E2E test invocation

docs/reference/config.md, internal/blockchain/ethereum/ethereum.go, internal/blockchain/ethereum/ethereum_test.go, internal/blockchain/ethereum/eventstream.go, internal/blockchain/fabric/eventstream.go, internal/blockchain/fabric/fabric.go, internal/blockchain/fabric/fabric_test.go, internal/coreconfig/coreconfig.go, internal/coremsgs/en_config_descriptions.go
Now, both ethconnect and fabconnect subscription names contain the namespace name. This means that events will now be delivered only to the callback handler for that namespace, instead of every single callback handler. Older subscriptions will still be delivered to all handlers.
=> Custom contract subscriptions now utilize namespaces

internal/apiserver/route_get_contract_api_by_name.go, internal/apiserver/route_get_contract_api_interface.go, internal/apiserver/route_get_contract_api_listeners.go, internal/apiserver/route_get_contract_apis.go, internal/apiserver/route_get_contract_interface.go, internal/apiserver/route_get_contract_interface_name_version.go, internal/apiserver/route_get_contract_interface_test.go, internal/apiserver/route_get_contract_interfaces.go, internal/apiserver/route_get_contract_listener_by_name_or_id.go, internal/apiserver/route_get_contract_listeners.go, internal/apiserver/route_post_contract_api_invoke.go, internal/apiserver/route_post_contract_api_listeners.go, internal/apiserver/route_post_contract_api_query.go, internal/apiserver/route_post_contract_interface_generate.go, internal/apiserver/route_post_contract_invoke.go, internal/apiserver/route_post_contract_query.go, internal/apiserver/route_post_new_contract_api.go, internal/apiserver/route_post_new_contract_api_test.go, internal/apiserver/route_post_new_contract_interface.go, internal/apiserver/route_post_new_contract_interface_test.go, internal/apiserver/route_post_new_contract_listener.go, internal/apiserver/route_put_contract_api.go, internal/apiserver/route_put_contract_api_test.go, internal/coremsgs/en_error_messages.go, internal/definitions/handler.go, internal/definitions/sender.go, internal/events/event_manager.go, internal/identity/identitymanager.go, internal/identity/identitymanager_test.go, internal/orchestrator/orchestrator.go
Now, multiparty-disabled namespaces can run without a blockchain plugin:
* All contract routes will be disabled
* Identity normalizations that rely on a blockchain plugin will either default to the specified input/default key or fail
* `aggregator` is not started within `EventManager`
=> Support tokens only namespaces

docs/tutorials/custom_contracts/ethereum.md, docs/tutorials/custom_contracts/fabric.md, docs/tutorials/fabric_remote.md
Signed-off-by: Sarthak Joshi <sarthakjoshi.in@gmail.com>
=> added documentation for connecting firefly to a remote fabric chaincode

go.mod, go.sum, internal/definitions/sender_contracts.go
depends on https://github.com/hyperledger/firefly-common/pull/25
=> remove namespace from `sender_contracts`

.github/workflows/go.yml
Each E2E job in the workflow matrix currently takes ~10 min, where the first ~5 min is just spent building the FireFly Docker image.
By building the Docker once upfront and sharing it across all jobs, each test job can be cut in half. This shaves 20-30 min off the combined runtime of the workflow jobs and makes more efficient use of the available workers.
As a small side benefit, the Docker image for each run is also stored as an artifact available for download.
=> Build Docker once to share with all E2E jobs

internal/events/token_pool_created.go, internal/events/token_pool_created_test.go, internal/events/tokens_approved.go, internal/events/tokens_approved_test.go, internal/events/tokens_transferred.go, internal/events/tokens_transferred_test.go, internal/orchestrator/orchestrator.go, internal/orchestrator/orchestrator_test.go, internal/tokens/fftokens/fftokens.go, internal/tokens/fftokens/fftokens_test.go, manifest.json, mocks/tokenmocks/plugin.go, pkg/tokens/plugin.go
Depends on:
https://github.com/hyperledger/firefly-tokens-erc1155/pull/84
https://github.com/hyperledger/firefly-tokens-erc20-erc721/pull/70
=> Use "poolData" instead of "namespace" in fftokens

internal/blockchain/ethereum/ethereum.go, internal/data/data_manager.go, internal/dataexchange/ffdx/dxevent.go, internal/dataexchange/ffdx/ffdx.go, internal/dataexchange/ffdx/ffdx_test.go, internal/definitions/handler.go, internal/definitions/handler_identity_claim.go, internal/definitions/handler_network_node_test.go, internal/definitions/handler_test.go, internal/definitions/sender.go, internal/definitions/sender_test.go, internal/identity/identitymanager.go, internal/networkmap/register_node.go, internal/networkmap/register_node_test.go, internal/orchestrator/orchestrator.go, internal/orchestrator/orchestrator_test.go, internal/privatemessaging/operations.go, internal/privatemessaging/operations_test.go, manifest.json, mocks/dataexchangemocks/plugin.go, pkg/dataexchange/plugin.go
~~In a chain with #915~~
Depends on https://github.com/hyperledger/firefly-dataexchange-https/pull/62
UPDATE: found a number of bugs while adding E2E tests - so #918 contains everything from this PR, some additional fixes, and an E2E test. The comments below are still relevant though.
FireFly can now support many local namespaces that map to a single remote namespace (for multi-tenancy purposes). Each of these local namespaces may have their own "node" within FireFly, but they may all be sharing a single DX plugin. This change adds a "nodeName" qualifier to many of the dataexchange plugin calls, along with a specific implementation in the FFDX plugin code, to allow many nodes to exist behind a single DX.
Implementation outline:
* For newly created nodes, the FFDX connector will append a …
=> Add node-specific suffix to DX endpoint "id"

Makefile
Avoids surprising changes to linter rules.
Also looks like the current "latest" version of golangci-lint is Go 1.19 only, and we don't want to upgrade just yet.
=> Pin golangci-lint to v1.47.3 instead of latest

go.mod, go.sum, internal/blockchain/ethereum/ethereum.go, internal/blockchain/ethereum/ethereum_test.go, internal/coremsgs/en_config_descriptions.go
- Support the `TransactionUpdate` type of websocket payload - which just updates the operation, while leaving it in `Pending` status (rather than marking it success/fail)
- Support events with an `0x12345:` address prefix on the signature
=> Updates for EVMConnect support (with EthConnect cross-compatibility)

.gitignore, docs/tutorials/fabric_remote.md
Signed-off-by: Kmilo Denis Glez <kmilo.denis.glez@gmail.com>
=> Update .gitignore: ignoring .idea path

internal/assets/token_pool.go, internal/blockchain/ethereum/config.go, internal/blockchain/ethereum/ethereum_test.go, internal/blockchain/fabric/config.go, internal/blockchain/fabric/fabric_test.go, internal/broadcast/manager.go, internal/broadcast/manager_test.go, internal/multiparty/manager.go, internal/privatemessaging/privatemessaging.go, test/e2e/run.sh
* Always populate Operation namespace from Managers instead of from other objects
* Actually store pending blob upload Operations
* Other misc cleanup identified while doing E2E and perf test runs
=> Fix bugs with Operations (and other minor fixes)

internal/txcommon/txcommon_test.go
=> Remove unneeded sleep from txcommon test

internal/dataexchange/ffdx/ffdx.go, internal/dataexchange/ffdx/ffdx_test.go, manifest.json
Depends on https://github.com/hyperledger/firefly-dataexchange-https/pull/67
=> Advertise full node name (with suffix) to DX

go.mod, go.sum, internal/apiserver/server.go, test/e2e/client/restclient.go, test/e2e/e2e.go, test/e2e/runners/ethereum_multiparty_test.go
Biggest change is to the HTTP Server to allow requests longer than 15s to complete without the client getting an EOF.
See https://github.com/hyperledger/firefly-common/pull/31
=> Changes to support E2E tests with confirmations, where requests might be slow

cmd/firefly.go, db/migrations/postgres/000096_add_namespace_to_message_indexes.up.sql, internal/database/sqlcommon/message_sql.go, internal/database/sqlcommon/message_sql_test.go, internal/events/aggregator.go, internal/events/aggregator_rewind.go, internal/events/aggregator_rewind_test.go, mocks/databasemocks/plugin.go, pkg/database/plugin.go
Ensure batch ID queries match the current indexes (to avoid sequential scan), and improve the caching in aggregator when processing a group of pins.
=> Performance improvements for batch lookups

internal/privatemessaging/groupmanager.go, internal/privatemessaging/groupmanager_test.go, internal/txcommon/txcommon.go
Insert local group only after inserting groupinit message.
This ensures no other threads pick up on the group before the
message is sequenced.
Update transaction cache after initial insert.
=> Fix group race condition, optimize transaction cache

.github/workflows/integration.yml
`exclude` was not correctly handling arrays, so it has been updated to explicitly define all excluded combinations
list of jobs that will be executed now (courtesy of [act](https://github.com/nektos/act)):
-  `[blockchain-provider:besu database-type:postgres test-suite:TestEthereumMultipartyE2ESuite]`
- `[blockchain-provider:geth database-type:sqlite3 test-suite:TestEthereumMultipartyE2ESuite]`
- `[blockchain-provider:geth database-type:postgres test-suite:TestEthereumMultipartyE2ESuite]`
- `[blockchain-provider:geth database-type:sqlite3 test-suite:TestEthereumGatewayE2ESuite]`
- `[blockchain-provider:geth database-type:postgres test-suite:TestEthereumGatewayE2ESuite]`
- `[blockchain-provider:besu database-type:sqlite3 test-suite:TestEthereumGatewayE2ESuite]`
- `[blockchain-provider:besu …
=> fix integration matrix `exclude`

docs/reference/config.md, internal/blockchain/ethereum/ethereum.go, internal/blockchain/fabric/fabric.go, internal/coreconfig/coreconfig.go, internal/coremsgs/en_config_descriptions.go, internal/events/aggregator.go, internal/events/event_manager.go, internal/operations/manager.go, internal/privatemessaging/privatemessaging.go, internal/privatemessaging/privatemessaging_test.go, internal/txcommon/txcommon.go, internal/txcommon/txcommon_test.go
Caches may be limited on size (if the items advertise their Size) or on
number of items. Since most cached items do not expose a Size, the limit
should be set on number of items alone.
Picked numbers pretty much at random, so I'm open to feedback if they
should be higher or lower, or if any of these items should get a Size method
to do size estimation.
I've tagged with "migration_consideration" since I have renamed a few
config keys, but I don't think they're widely used.
=> Adjust defaults for all cache items that don't expose a Size

docs/reference/config.md, ffconfig/migrate/migrations.go, ffconfig/migrate/migrations_test.go, internal/apiserver/server.go, internal/apiserver/server_test.go, internal/blockchain/ethereum/ethereum.go, internal/blockchain/fabric/fabric.go, internal/coreconfig/coreconfig.go, internal/coremsgs/en_config_descriptions.go, internal/multiparty/manager.go, internal/multiparty/manager_test.go, internal/namespace/manager.go, test/e2e/common.go
FireFly should continue to work when run against a config file from 1.0.x.
Since this references 1.0.4, it should go in after https://github.com/hyperledger/firefly/pull/982 is merged and released as 1.0.4.
=> Fix bugs when running with an old config file

cmd/firefly.go, cmd/firefly_test.go
Fixes https://github.com/hyperledger/firefly/issues/993
We need to wait for the `startFirefly` routine to exit, before we can safely restart it.
This means a second channel to distinguish exit, from an error.
A secondary fix in this PR, is to stop/restart the debug server after the reset - previously it was never stopped.
=> Wait for server to exit, before restarting for reset

internal/blockchain/ethereum/ethereum.go
Found while diagnosing https://github.com/hyperledger/firefly/issues/990#issuecomment-1221077085, that we didn't include the underlying error when we had a problem parsing the input for the Ethereum implementation of the `/api/v1/contracts/interfaces/generate` endpoint.
=> Propagate the underlying parse error

test/e2e/e2e.go, test/e2e/multiparty/common.go, test/e2e/multiparty/identity.go, test/e2e/run.sh
Signed-off-by: Anna Jackson <anna.jackson@kaleido.io>
Adds one of the proposed negative test cases from https://github.com/hyperledger/firefly/issues/944
> Registering invalid identities- keys that have already been used
=> Add e2e test which attempts to register an invalid identity by reusing a key

internal/dataexchange/ffdx/ffdx.go, internal/dataexchange/ffdx/ffdx_test.go
DX's being implemented in languages like Typescript do not treat `null` as a valid, empty JSON array which was causing problems. Core would get a `500` from DX:
```
{"@timestamp":"2022-08-24T17:49:59.714Z","breq":"8CWznOwK","dx":"https","level":"debug","message":"==\u003e POST http://firefly-dx.infra.svc:3000/api/v1/init","pid":"1"}
{"@timestamp":"2022-08-24T17:49:59.720Z","breq":"8CWznOwK","dx":"https","level":"error","message":"\u003c== POST http://firefly-dx.infra.svc:3000/api/v1/init [500] (5.67ms)","pid":"1"}
```
and we'd see DX error with:
```
2022-08-24T17:49:52.646Z [ERROR]: Unexpected token n in JSON at position 0 lib/request-error.ts
```
=> Ensuring Empty List is Provided for FFDX Init on Zero Peer Nodes

auditevents/main.go
This is an alternative to #998, written in Go rather than bash.
Not sure where we should put scripts if we keep adding them... do we just keep adding root level folders like this?
=> Add tool for auditing blockchain event order

internal/database/postgres/postgres.go, internal/database/postgres/postgres_test.go, internal/database/sqlcommon/event_sql.go, internal/database/sqlcommon/event_sql_test.go, internal/database/sqlcommon/provider.go, internal/database/sqlcommon/provider_mock_test.go, internal/database/sqlcommon/sqlcommon.go, internal/database/sqlcommon/sqlcommon_test.go
Advisory locks are identified with a 64-bit integer, so I've put in place a
rudimentary mapping from namespace names to a (probably) unique int64.
This should ensure consistent ordering for the writes to the events table
within a particular namespace, without blocking reads or other namespaces.
=> Use advisory lock instead of exclusive lock on events table

docs/swagger/swagger.yaml, internal/apiserver/route_get_contract_listener_by_name_or_id.go, internal/apiserver/route_get_contract_listener_by_name_or_id_test.go, internal/apiserver/route_get_subscription_by_id.go, internal/apiserver/route_get_subscription_by_id_test.go, internal/blockchain/ethereum/ethereum.go, internal/blockchain/ethereum/ethereum_test.go, internal/blockchain/ethereum/eventstream.go, internal/blockchain/fabric/fabric.go, internal/blockchain/fabric/fabric_test.go, internal/contracts/manager.go, internal/contracts/manager_test.go, internal/coremsgs/en_api_translations.go, internal/coremsgs/en_error_messages.go, internal/orchestrator/orchestrator.go, internal/orchestrator/subscriptions.go, internal/orchestrator/subscriptions_test.go, mocks/blockchainmocks/plugin.go, mocks/contractmocks/manager.go, mocks/orchestratormocks/orchestrator.go, pkg/blockchain/plugin.go, pkg/core/contract_listener.go, pkg/core/subscription.go
If the `fetchstatus` query param is supplied when querying `subscriptions` or `listeners` by ID, firefly will return additional status information, if it is available.
FF environments connected to evm connectors will return listener checkpoint formation under the `status` key.
Example query: `http://localhost:5000/api/v1/namespaces/default/contracts/listeners/92e3bc0c-3c3f-455b-81d3-4124a0270b1d?fetchstatus`
Response:
```
{
"id": "92e3bc0c-3c3f-455b-81d3-4124a0270b1d",
"interface": {
"id": "30775d45-61af-4f76-9d35-69b5d8ffbf42"
},
"namespace": "default",
"name": "0182f410-a686-79ed-23a5-ac8c62acbf51",
"backendId": "0182f410-a686-79ed-23a5-ac8c62acbf51",
"location": {
"address": "0x62d365e68fc55845ba904acef688feba7a598c9c"
},
"created": "2022-08-31T13:21:48.1687995Z",
"event": {
"name": …
```
=> Add status information for subscriptions & contract listeners

internal/events/token_pool_created.go, internal/tokens/fftokens/fftokens.go
The following panic was occurring when using an ERC-20 connector, in an environment that had been migrated from V1.0, so had the `ff_system` namespace event listener running.
The panic failed the request to create the token pool with a `500`, but the token pool was created successfully.
The problem is specific to a `200 OK` return (rather than `202 Accepted`) return from the token connector on `/api/v1/createpool`, because there is no `blockchain` field (translated to `pool.Event` during processing) in the data from the connector on that path.
So this line would panic, dereferencing the `pool.Event.ProtocolID`:
https://github.com/hyperledger/firefly/blob/c5cc7ede18e6127277ebce4715baffb69d2ca513/internal/events/token_pool_created.go#L172
I've tidied up various logging along the way.
I also …
=> Prevent panic on ff_system namespace for synchronous token pool creation in V1.0 migrated env

auditevents/main.go
Need to keep requesting new chunks of events even if the previous chunk
contained no matches.
=> Fix sequence query in auditevents

db/migrations/postgres/000099_fix_blockchainevent_protocolid_index.down.sql, db/migrations/postgres/000099_fix_blockchainevent_protocolid_index.up.sql, db/migrations/sqlite/000099_fix_blockchainevent_protocolid_index.down.sql, db/migrations/sqlite/000099_fix_blockchainevent_protocolid_index.up.sql, internal/database/sqlcommon/blockchainevents_sql_test.go
Because listener_id is NULL for these events, we need separate indexes for when it is NULL and not NULL.
=> Properly enforce uniqueness of BatchPin blockchain events

internal/dataexchange/ffdx/ffdx.go, internal/identity/identitymanager.go, internal/identity/identitymanager_test.go, internal/orchestrator/status.go, internal/orchestrator/status_test.go, internal/privatemessaging/privatemessaging.go, internal/privatemessaging/recipients.go, test/e2e/multiparty/contract_migration.go
Reverts #1035 
Fixes #1032
Fixes #1045
=> Consistently fall back to ff_system for legacy identity lookups

db/migrations/postgres/000099_fix_blockchainevent_protocolid_index.up.sql, db/migrations/sqlite/000099_fix_blockchainevent_protocolid_index.up.sql
Should fix any environments that got into a bad state between 0e559460a4ee2c68a66c23a5ca108bc98e7dfded (1.1.0-rc.1) and d75f2d4a0cd689df174d57d8e40d4c623c129e0d (1.1.0-rc.4).
=> Delete duplicate blockchainevents when migrating

.github/workflows/docker_main.yml, .github/workflows/docker_release.yml, Makefile, docker_build.sh, test/e2e/run.sh
This PR switches to the `docker buildx` command for building images for multiple CPU architectures. Currently, the build jobs are set up to build `linux/amd64` and `linux/arm64`. This is set in the `Makefile`. Because building a Docker image for a non-native CPU architecture is very slow (because it's emulated), mutiarch builds are not the default when running `make docker`. Instead a new command, `make docker-multiarch` has been added, which is used by our GitHub Actions.
> **NOTE:** From my testing `docker buildx` seems to return status 0, despite the fact that it may have failed to push to a repository. This can result in false positives for our GitHub Actions. I looked into this and it seems to be an open issue with `buildx` https://github.com/docker/buildx/issues/732
=> Use docker buildx for multiarch builds

internal/contracts/manager.go
~~Fixes error where namespace was not set when resolving contract API on create. This resulted in contract listener url's being broken in the `POST` response.~~
When generating contract URL's, always use the `ContractManager` namespace.
closes #1067
=> use `cm.namespace` when generating contract URL's 

db/migrations/postgres/000100_allow_null_listener_location.down.sql, db/migrations/postgres/000100_allow_null_listener_location.up.sql, db/migrations/sqlite/000100_allow_null_listener_location.down.sql, db/migrations/sqlite/000100_allow_null_listener_location.up.sql, internal/blockchain/ethereum/ethereum.go, internal/blockchain/ethereum/ethereum_test.go, internal/blockchain/ethereum/eventstream.go, internal/blockchain/fabric/eventstream.go, internal/blockchain/fabric/fabric.go, internal/blockchain/fabric/fabric_test.go, internal/contracts/manager.go, internal/contracts/manager_test.go
=> make contract listener `location` optional

internal/definitions/definition_handler_identity_claim.go, internal/definitions/definition_handler_identity_update.go, internal/definitions/definition_handler_identity_update_test.go
Testing patching Node identity for Cert cycling, I found that in v1.0 we were missing the API from the Swagger, but it did exist
`PATCH` `namespaces/{ns}/identities/{iid}`
However, attempt to run it for a node resulted in the following - due to a discrepancy between the checking for the author of the message between identity creation, and identity update:
`[2022-09-22T22:39:53.629Z]  WARN node_0: Invalid identity update message 2ac79c71-3983-45a4-8942-7f1bc124225b - wrong author: did:firefly:org/org_0 dbtx=reAmSQrS role=aggregator`
This PR is a V1.0 stream fix to correct this. A separate PR will be needed for the V1.1 stream - in #1074
=> V1.0.x fix: Allow update of node using parent org identity

docs/reference/config.md, docs/reference/types/_includes/subscription_description.md, internal/coremsgs/en_config_descriptions.go, internal/events/eifactory/factory.go, internal/events/webhooks/webhooks.go, internal/events/webhooks/webhooks_test.go, internal/namespace/manager.go
Raised from #1025 
- Adds better logging
- Ensures we do a `DeliveryResponse` in the case of a non-`reply`, non-`fastack` webhook subscription
- Disabled `fastack` when `reply` is configured, as the reply would not be sent otherwise
- (Re)instate the lost `events` section in the config docs
- Correct the docs to reflect that if you want to retry on non-`2xx` error codes, you need to set `events.webhooks.retry`
=> Fix acknowledgement for webhooks in non-reply, non-fastack cases

.github/workflows/docker_main.yml, .github/workflows/docker_release.yml
Resolves https://github.com/hyperledger/firefly/issues/1086
This moves the bash evaluation up a step, because it cannot be used inside the `with:` field for the docker build and push action
=> Fix docker image labels

cmd/firefly.go, docs/reference/config.md, internal/coreconfig/coreconfig.go, internal/coreconfig/coreconfig_test.go, internal/coremsgs/en_config_descriptions.go
It's difficult using the go pprof debug utility when running in a container since the network interface it binds to defaults to localhost. This PR makes 2 changes:
1. Make the interface address configurable
2. Change the default interface to "*"
It still requires changes to the docker run command or docker compose overrides file to get a route through to the debug listener, but doesn't require you to rebuild firefly.
=> Allow listening for go debug on all interfaces, not just localhost

docs/tutorials/custom_contracts/ethereum.md
Signed-off-by: Matthew Whitehead <matthew.whitehead@kaleido.io>
=> Fix the example ff deploy command to specify ethereum

docs/overview/multiparty_features.md
Signed-off-by: Chengxuan Xing <chengxuan.xing@kaleido.io>
=> Fix typo in multiparty_features.md

docs/tutorials/tokens/erc1155.md
Fix typo in the erc155 tutorial init command. `ff init -t erc-1155` to `ff init -t erc1155`
Signed-off-by: Ander Dorado <71599694+ander-db@users.noreply.github.com>
=> Fix typo in erc1155.md

db/migrations/postgres/000044_add_tokenpool_state.up.sql, db/migrations/sqlite/000044_add_tokenpool_state.up.sql, docs/reference/types/tokenpool.md, docs/swagger/swagger.yaml, internal/events/token_pool_created.go, internal/events/token_pool_created_test.go, pkg/core/tokenpool.go
After > 1 year, I think we can remove the special handling for this long-deprecated migration path around pre-0.11.0 token pools.
=> Minor cleanup in token pool event processing

docs/reference/microservices/fftokens.md
Document the new parameters and APIs that were added as part of [FIR-16](https://github.com/hyperledger/firefly-fir/pull/16).
=> Add FIR-16 enhancements to fftokens documentation

internal/contracts/manager.go, internal/contracts/manager_test.go, internal/database/sqlcommon/ffi_errors_sql.go, internal/database/sqlcommon/ffi_errors_sql_test.go, internal/metrics/metrics_test.go, mocks/databasemocks/plugin.go, pkg/database/plugin.go
There was no coverage of the DB interface for FFI Errors, and oddly there was a difference in the query interface to all other DB packages. Unsure why that was, so I made it consistent.
=> Fix coverage gap in FFIErrors, and make DB interface consistent

docs/tutorials/tokens/erc1155.md, docs/tutorials/tokens/erc20.md, docs/tutorials/tokens/erc721.md
Part of [FIR-16](https://github.com/hyperledger/firefly-fir/pull/16).
This links out to the READMEs of both token connectors for "more details", so these PRs are relevant to be merged alongside this one:
https://github.com/hyperledger/firefly-tokens-erc20-erc721/pull/108
https://github.com/hyperledger/firefly-tokens-erc1155/pull/107
=> Add docs on passing ABI info to token pools

docs/reference/types/_includes/subscription_description.md
Spotted this reading the web hooks docs. Assume it should say "WebSockets"
Signed-off-by: Matthew Whitehead <matthew.whitehead@kaleido.io>
=> Typo - change WebHooks to WebSockets

db/migrations/postgres/000104_add_tokenpool_interface.up.sql, db/migrations/sqlite/000104_add_tokenpool_interface.up.sql
Loading a NULL value into a Go string is unsupported.
Default this column to `''` so that pre-existing token pools receive that value instead of a `NULL`.
Note that this is an alteration to a migration file added in https://github.com/hyperledger/firefly/pull/1123, so wouldn't be executed by any installation that has already picked up that change. Since it hasn't yet been released, this shouldn't cause any problems.
=> Default token pool interfaceFormat to empty string

internal/apiserver/ffi2swagger.go, internal/apiserver/ffi2swagger_test.go
Adds `key` and `idempotencyKey` as well as descriptions for those and `input` and `options`.
=> Add missing fields and descriptions to custom contract API swagger

internal/identity/identitymanager.go, internal/identity/identitymanager_test.go
In the specific case of the `multipartyRootVerifier` we were not calling the `ResolveInputSigningKey` function on the Blockchain plugin, meaning a corner case where #1141 was not causing an invoke of the plug point.
=> Verify the default key in all cases

.github/workflows/go.yml, .github/workflows/integration.yml, internal/database/sqlcommon/pin_sql.go, manifest.json, test/e2e/multiparty/tokens.go, test/e2e/run.sh
This PR updates the `manifest.json` with the latest version of each dependency service, the latest CLI, the latest UI, and sets `evmconnect` to be the new default for E2E tests. Ethconnect is still tested, but it now takes a back seat compared to evmconnect.
=> v1.2.0-alpha.1

internal/events/webhooks/webhooks.go, internal/events/webhooks/webhooks_test.go
Resolves https://github.com/hyperledger/firefly/issues/1155
This PR changes the behavior of webhook callbacks in several ways:
- If `reply` is specified on the subscription it no longer panics if there is no Message on the event (such as is the case with custom contract events)
- If `withData` is specified subscription, but no Message is on the event, the event payload itself will still be sent
This means that subscriptions can be setup with either the `reply` and `withData` fields set (or both) and still use the same subscription for custom contract events as well.
=> Fix panic on webhooks without messages

internal/apiserver/route_get_namespace_test.go, internal/apiserver/server.go, internal/apiserver/server_test.go, internal/apiserver/spi_routes.go, internal/coremsgs/en_error_messages.go, internal/events/webhooks/webhooks.go, internal/events/webhooks/webhooks_test.go, internal/namespace/manager.go, internal/namespace/manager_test.go, mocks/namespacemocks/manager.go
Backports the following:
#1130 - crash fix only, not the extra test coverage (much of which was not applicable to this branch)
#1156
=> Backport crash fixes to release-1.1 branch

docker_build.sh
Greatly reduces incremental build time for "make docker".
=> Keep Docker state between builds

.github/workflows/docker_main.yml, .github/workflows/docker_release.yml
Due to a recent change in the docker/build-push-action GitHub Action https://github.com/docker/build-push-action/issues/778 our images stopped having their manifests published properly. This PR updates our GitHub Actions to use a newer version of the Action, and restores the previously working behavior. I was able to test this on my own fork and created https://github.com/nguyer/firefly/pkgs/container/firefly/67526987 which has a good manifest in it.
=> Update to docker/build-push-action@v4

internal/batch/batch_manager.go
Messages from the same identity but different signing keys must be processed into different batches. If the signing key of the message does not match the signing key of the batch, the message will be rejected.
Fixes #1173
=> Include signing key in batch processor identifier

.github/workflows/docker_main.yml, .github/workflows/docker_release.yml, internal/blockchain/common/common.go, manifest.json
This brings the contract address of a deployed contract all the way through to the transaction output when deploying a new smart contract. This shows up in a `JSONAny` field called `contractLocation` and looks like this in FireFly:
```json
...
"output": {
"headers": {
"requestId": "default:aa155a3c-2591-410e-bc9d-68ae7de34689",
"type": "TransactionSuccess"
},
"contractLocation": {
"address": "0x24746b95d118b2b4e8d07b06b1bad988fbf9415d"
},
"protocolId": "000000000024/000000",
"transactionHash": "0x32d1144091877266d7f0426e48db157e7d1a857c62e6f488319bb09243f0f851"
},
...
```
=> Add contractLocation field to deploy transaction output

docs/tutorials/broadcast_data.md, docs/tutorials/private_send.md
I assume this should say `multi-part` (as in the MIME type) as opposed to `multi-party`
Signed-off-by: Matthew Whitehead <matthew1001@gmail.com>
=> Fix typo in private & broadcast blob upload docs

test/e2e/run.sh
Previously we were passing the `--blockchain-node` flag for all integration tests. The `ff init fabric` subcommand does not support this flag though, so it fails to create the test stack.
Here is an example of a failed run where this happened: https://github.com/hyperledger/firefly/actions/runs/4189374980/jobs/7261623960#step:6:139
```
ff -v --ansi never init fabric --prometheus-enabled --database sqlite3 firefly_e2e 2 --blockchain-node fabric --token-providers erc20_erc721 --manifest ../../manifest.json --sandbox-enabled=false --multiparty=true
Error: unknown flag: --blockchain-node
```
=> Fix nightly integration tests

docs/tutorials/chains/fabric_test_network.md
While re-running this tutorial I noticed that one of the paths to a key seemed incorrect. I have successfully run through it using the updated path in this PR.
=> Fix path in Fabric test-network tutorial

internal/database/sqlcommon/data_sql.go
Need to pass requestConflictEmptyResult=true on this path, the same as we do on the postgres path.
Fixes #1196
=> Fail gracefully when inserting many data rows on sqlite

db/migrations/postgres/000106_add_message_transactions.down.sql, db/migrations/postgres/000106_add_message_transactions.up.sql, db/migrations/sqlite/000106_add_message_transactions.down.sql, db/migrations/sqlite/000106_add_message_transactions.up.sql, docs/reference/types/message.md, docs/swagger/swagger.yaml, internal/assets/token_approval.go, internal/assets/token_approval_test.go, internal/assets/token_transfer.go, internal/assets/token_transfer_test.go, internal/batch/batch_processor.go, internal/broadcast/manager.go, internal/broadcast/manager_test.go, internal/coremsgs/en_struct_descriptions.go, internal/database/sqlcommon/message_sql.go, internal/database/sqlcommon/message_sql_test.go, internal/events/aggregator.go, internal/events/aggregator_test.go, internal/events/persist_batch.go, internal/privatemessaging/privatemessaging.go, internal/privatemessaging/privatemessaging_test.go, pkg/core/message.go, pkg/database/plugin.go
Propagate the `batch_pin` transaction ID onto the message when the batch is assembled (sender) or when it is persisted (receiver), as a new `txid` field.
For token transfers and approvals that come with a message, store the `token_transfer` or `token_approval` transaction details on the message up-front, as a new `txparent` field.
Illustration of changes to the message object:
This does mean the allocation of the `token_transfer` or `token_approval` transaction ID happens earlier and outside a database transaction, but I don't see a problem with this.
This probably supersedes both #1157 and #1162, as I think it's a cleaner route toward solving that problem _and_ teeing up [FIR-17](https://github.com/hyperledger/firefly-fir/pull/17).
=> Add "txid" and "txparent" to messages

docs/swagger/swagger.yaml, internal/coremsgs/en_api_translations.go, internal/orchestrator/orchestrator.go
Fixes #1200 
I also clarified the API description to point out the important caveat that the aggregator will only acknowledge a rewind to an undispatched pin. For error recovery purposes, there may be a separate piece of work to be able to force a rewind to a pin even if it's already dispatched.
Also, it's worth noting that there's a double lookup in the case of a "sequence" based rewind - we resolve the sequence number to a batch (in `orchestrator.RewindPins`), then resolve the batch back to a sequence number (in `aggregator.rewindOffchainBatches`). It seems to work well enough, but there's some room for a more direct rewind path.
=> Fix spelling of "sequence" rewind and clarify API description

internal/batch/batch_manager_test.go, internal/batch/batch_processor.go, internal/batch/batch_processor_test.go, internal/database/sqlcommon/batch_sql.go, internal/database/sqlcommon/batch_sql_test.go, internal/events/batch_pin_complete_test.go, internal/events/dx_callbacks_test.go, internal/events/persist_batch.go, internal/events/persist_batch_test.go, internal/events/ss_callbacks_test.go, mocks/databasemocks/plugin.go, pkg/database/plugin.go
When persisting an off-chain batch initially received from data exchange or shared storage, it should always be an insert. If the batch exists, just move on. Otherwise we may accidentally revert a confirmed batch to its previous state if it happens to get redelivered.
Bonus: In addition to preventing bugs, this should give a tiny performance boost due to the optimistic batch insert.
=> Replace "UpsertBatch" with "InsertOrGetBatch"

internal/events/event_poller.go, internal/events/event_poller_test.go
After a rewind to recover from an missed batch (an occurrence of https://github.com/hyperledger/firefly-evmconnect/issues/53) I observed a slow recovery, and the logs seemed to show the Event Aggregator pausing for long periods rather than screaming through all the messages.
Investigating the code, I did not find anything that would prevent it waiting the full time in the case of having read a full page of events. This would mean when paging through old events a long way before the head, it could be very slow to recover.
> Note, you only notice this when in recovery mode after a rewind when events are not arriving frequently - as in that case there are no shoulder taps to naturally wake the event loop.
>
> Also, you only notice this when there is more than a full page (200) inflight pins …
=> Re-poll immediately on full batch

internal/events/event_poller.go, internal/events/event_poller_test.go
=> v1.1 backport: Re-poll immediately on full batch

internal/coremsgs/en_error_messages.go, internal/definitions/handler_contracts.go, internal/definitions/handler_identity_update.go, internal/definitions/handler_identity_verification.go, internal/definitions/handler_tokenpool.go, internal/definitions/sender_tokenpool.go, internal/definitions/sender_tokenpool_test.go, test/e2e/gateway/tokens_only.go
We saw if `broadcastName` was set on a tokens plugin, token pools would fail to create within gateway namespaces:
```
[2023-03-01T20:25:10.568Z] ERROR Failed to activate token pool 'f2de67bb-5adf-4b98-ac06-7d25a19805ad': FF10272: Unknown tokens plugin 'erc20-erc721' ns=cok pid=1 role=event-manager
[2023-03-01T20:25:10.568Z] DEBUG fftokens updating operation cok:fb435cab-a2a5-4d1a-af28-f0bf84840c0b status=Failed error=FF10272: Unknown tokens plugin 'erc20-erc721' ns=cok pid=1
[2023-03-01T20:25:10.568Z] DEBUG SQL-> begin dbtx=N1fXw8pi ns=cok pid=1
[2023-03-01T20:25:10.568Z] DEBUG SQL<- begin dbtx=N1fXw8pi ns=cok pid=1
[2023-03-01T20:25:10.569Z] DEBUG SQL-> update operations dbtx=N1fXw8pi ns=cok pid=1
[2023-03-01T20:25:10.569Z] DEBUG SQL<- update operations affected=1 dbtx=N1fXw8pi ns=cok …
```
=> [tokens] Only Use broadcastName for Multi-Party Namespaces

internal/database/sqlcommon/blockchainevents_sql.go
This is causing blockchain event inserts to incorrectly be logged as message inserts.
=> Fix logging of blockchain event inserts

internal/txcommon/txcommon.go, internal/txcommon/txcommon_test.go
There are multiple paths that record the blockchainID for a transaction. Along this path, we were updating the column in the database but not the cache - resulting in this field being intermittently out of sync.
=> Ensure cached transaction gets updated with new blockchain IDs

internal/events/event_manager.go, internal/events/token_pool_created.go, internal/events/token_pool_created_test.go, internal/tokens/fftokens/fftokens.go, internal/tokens/fftokens/fftokens_test.go, mocks/eventmocks/event_manager.go, mocks/tokenmocks/callbacks.go, pkg/tokens/plugin.go
When a token pool is created, the token connector can either confirm the token pool:
1. Synchronously if the token pool exists already on-chain - with a `200` return code
2. Asynchronously when using a factory contract - with a `202` return code, followed at some point with a websocket event
At this confirm stage, in a multi-party enabled namespace, the token pool is currently automatically published via .broadcast to all members of the network.
This automatic publishing occurs on the organization signing key, which might be different to the original key used to create the token pool on-chain (in the asynchronous case). This automated publishing is a little problematic for authentication checking based on the REST API context of the original token pool creation in the async case, because …
=> Propagate API context to announce in sync token pool creation cases

internal/definitions/sender.go, internal/definitions/sender_contracts_test.go, internal/definitions/sender_datatype_test.go, internal/definitions/sender_test.go, internal/definitions/sender_tokenpool_test.go, internal/events/event_manager.go, internal/events/token_pool_created.go, internal/events/token_pool_created_test.go, internal/tokens/fftokens/fftokens.go, internal/tokens/fftokens/fftokens_test.go, mocks/eventmocks/event_manager.go, mocks/tokenmocks/callbacks.go, pkg/tokens/plugin.go
Since 1.1 we've had both an org identity (required for mulit-party), and a default namespace identity (optional).
The code for definition broadcasts must use the org identity for that broadcast to be accepted, but the code was using the same priority as generic API calls - which use the NS default identity in preference.
This PR updates that so it's always the org identity, and the call will not fall-back to the default.
> Found this while discussing https://github.com/hyperledger/firefly/pull/1222 and hence in a PR chain with that change
=> Ensure that when we broadcast we use the org identity, not the default NS identity

docs/reference/config.md, internal/apiserver/route_post_verifiers_resolve.go, internal/apiserver/route_post_verifiers_resolve_test.go, internal/blockchain/ethereum/address_resolver.go, internal/blockchain/ethereum/address_resolver_test.go, internal/blockchain/ethereum/config.go, internal/blockchain/ethereum/ethereum.go, internal/blockchain/ethereum/ethereum_test.go, internal/blockchain/fabric/fabric.go, internal/blockchain/fabric/fabric_test.go, internal/coremsgs/en_config_descriptions.go, internal/identity/identitymanager.go, internal/identity/identitymanager_test.go, mocks/blockchainmocks/plugin.go, mocks/identitymanagermocks/manager.go, pkg/blockchain/plugin.go
The address resolver interface is extremely useful as a checking/enforcement point for signing actions being accepted into the system. However, currently there is no way to distinguish between simply a call to `/api/v1/resolve` to request a resolution of an input string to a signing key from the plugin, vs. the other actions (messages, custom invoke, token ops) that actually accept a signing request into the system.
This PR adds a simple addition field of `.Intent` that is `lookup` for `/api/v1/resolve` and `sign` for all other actions, and is passed into the existing Go API to the blockchain connector, and Go templates on the remote API hook (ethereum plugin only).
=> Add "intent" to address resolver plugin interface and API

internal/blockchain/fabric/fabric.go, internal/blockchain/fabric/fabric_test.go, internal/coremsgs/en_error_messages.go
Closes https://github.com/hyperledger/firefly/issues/1206
Screenshot of a fabric operation with these changes:
=> Use the channel and signer to query transaction details from fabconnect

.github/workflows/integration.yml
This fixes the name of the uploaded log archives from each E2E run. The `blockchain-node` variable was not set, so it was an empty string, causing name collisions. This means that we are missing detailed logs from certain runs, making it hard to debug integration failures.
=> Fix archive name for integration test logs

internal/namespace/manager.go, test/e2e/e2e.go, test/e2e/multiparty/contract_migration.go
Partial fix for #1245
Somewhere in the refactoring of namespace manager, it looks like we ended up in a situation where we _initialize_ but do not _start_ the legacy "ff_system" namespace.
=> Actually start the legacy "ff_system" namespace when needed

internal/blockchain/ethereum/ethereum.go, manifest.json
When querying network version, look for the unique error codes returned by either ethconnect or evmconnect.
Partial fix for #1245
Depends on https://github.com/hyperledger/firefly-evmconnect/pull/67
=> Add support for evmconnect's "execution reverted" error code

internal/events/aggregator.go, internal/events/aggregator_test.go
This prevents inserting a group from a malformed "group init" message.
Possible/partial fix for https://github.com/hyperledger/firefly/issues/1247
=> Check message on-chain consistency before initializing context

docs/swagger/swagger.yaml, internal/batch/batch_manager_test.go, internal/batch/batch_processor.go, internal/batch/batch_processor_test.go, internal/coremsgs/en_api_translations.go, internal/database/sqlcommon/batch_sql.go, internal/database/sqlcommon/batch_sql_test.go, internal/events/batch_pin_complete_test.go, internal/events/dx_callbacks_test.go, internal/events/event_poller.go, internal/events/event_poller_test.go, internal/events/persist_batch.go, internal/events/persist_batch_test.go, internal/events/ss_callbacks_test.go, internal/orchestrator/orchestrator.go, mocks/databasemocks/plugin.go, pkg/database/plugin.go
When persisting an off-chain batch initially received from data exchange or shared storage, it should always be an insert. If the batch exists, just move on. Otherwise we may accidentally revert a confirmed batch to its previous state if it happens to get redelivered.
Backport of #1208, #1209, and #1204
=> v1.2: Replace "UpsertBatch" with "InsertOrGetBatch"

.github/workflows/go.yml, Makefile, internal/namespace/configreload.go, internal/namespace/configreload_test.go, internal/namespace/manager.go
Event after #1242 checked in, @awrichar saw an instance of #1250 in this test run, with slightly different symptoms https://github.com/hyperledger/firefly/actions/runs/4728313082/jobs/8389728445
~These are a nightmare to diagnose, as Go tests do not log start/end of tests (unless in full debug mode) so a `goroutine` bleading past the end of the test boundary is hard to debug. But with some staring, I believe the problem is that some tests was only waiting _once_ at the end for the reload, and because of that there's the possibility for timing to happen such that the reload is detected before the first initialization has completed.~
~This proposed change adds a wait in the middle~
> See additional diagnosis below
> - locking update to ensure state propagation issue due to a lack of locking …
=> Fix timing issue between Init and ConfigReload of Namespace Manager

internal/coremsgs/en_error_messages.go, internal/events/aggregator.go, internal/events/aggregator_test.go, internal/privatemessaging/groupmanager.go, internal/privatemessaging/groupmanager_test.go
Since we allow private messages to originate from an unregistered blockchain signing key,
we must also accept groupinit messages from the same (since the first private message
to a group will trigger group creation as a side-effect).
Fixes #1247
=> Accept private groupinit messages from any signing key

internal/events/aggregator.go, internal/events/aggregator_test.go
=> Do not retry after a rejected message

db/migrations/postgres/000108_create_contractapis_id_index.up.sql, db/migrations/sqlite/000108_create_contractapis_id_index.up.sql, internal/apiserver/route_post_new_contract_api.go
Also ensure ID is always unset when creating a new API.
Follow-up to #1292, #1275
=> Remove duplicates prior to adding unique index on contract API ID

internal/database/sqlcommon/tokenpool_sql.go, internal/database/sqlcommon/tokenpool_sql_test.go
Since there is a unique index on pool locators, it must be checked during token pool upsert.
This behavior will be changing again in #1261, but this is a more immediate fix without pulling in all of that.
=> Handle duplicate pool locators properly

docs/reference/config.md, internal/coremsgs/en_config_descriptions.go, internal/dataexchange/ffdx/config.go, internal/dataexchange/ffdx/ffdx.go, internal/tokens/fftokens/config.go, internal/tokens/fftokens/fftokens.go, internal/tokens/fftokens/fftokens_test.go
Make this consistent with what we did for FFDX, and prevents a scenario on startup as seen in the integration test where a token event comes in before the namespace is started:
```
firefly_core_0_1  | [2023-04-30T00:35:08.431Z] DEBUG Calling TokenPoolCreated callback. Locator='address=0x8875e026c26cedc2ab9880ac56d31e328428db73&schema=ERC20WithData&type=fungible' TX=token_pool/66fffabe-5b11-4118-abc2-50b95877654d pid=1 proto=fftokens role=event-loop
firefly_core_0_1  | [2023-04-30T00:35:08.431Z] ERROR Event loop exiting (FF10446: Namespace 'default' is not started). Terminating server! pid=1 proto=fftokens role=event-loop
```
Also made a change to both FFDX and FFTokens to split `eventRetry` out from `retry` in the config, as I realized looking at this PR that the config was overlapping …
=> Retry tokens events consistent with FFDX, as we cannot push back nack

internal/events/aggregator.go, internal/events/aggregator_test.go
It is not possible for a group init message to fail at this phase. If it fails, it must fail earlier. If it makes it to dispatch, it should flow through to confirm.
Fixes #1308
=> Confirm group init messages during dispatch

internal/events/aggregator.go
=> Perform nextpin calculations for both confirmed and rejected messages

internal/blockchain/common/common.go, internal/blockchain/common/common_test.go, internal/blockchain/ethereum/ethereum.go, internal/blockchain/ethereum/ethereum_test.go, internal/blockchain/fabric/fabric.go, internal/blockchain/fabric/fabric_test.go, internal/events/batch_pin_complete.go, internal/events/batch_pin_complete_test.go, internal/events/blockchain_event.go, internal/events/blockchain_event_test.go, internal/events/event_manager.go, internal/events/network_action.go, internal/events/network_action_test.go, internal/orchestrator/bound_callbacks.go, internal/orchestrator/bound_callbacks_test.go, internal/tokens/fftokens/fftokens_test.go, mocks/blockchainmocks/callbacks.go, mocks/eventmocks/event_manager.go, pkg/blockchain/plugin.go
One of the outstanding observations from the performance testing in V1.2 was that we are performing a DB commit for each Blockchain event.
These are sequential on the single logical delivery thread from the blockchain connector (which currently is server-wide, although that should itself become namespace-wide).
This PR proposes that instead we update all the internal callback interfaces, to propagate the batch of events that come in over the wire from the connector, through to the event processor.
This means a few things handled in this PR:
1. Handling a batch that contains events of multiple types -  Batch Pin, Network Action, or custom Blockchain Event Listener
2. Handling a batch that needs different events dispatching to different namespaces
3. Continuing to handle old events that …
=> Process batch of events from Blockchain connector, in a single DB TX

db/migrations/postgres/000114_add_message_reject_reason.down.sql, db/migrations/postgres/000114_add_message_reject_reason.up.sql, db/migrations/sqlite/000114_add_message_reject_reason.down.sql, db/migrations/sqlite/000114_add_message_reject_reason.up.sql, docs/reference/types/message.md, docs/swagger/swagger.yaml, internal/coremsgs/en_error_messages.go, internal/coremsgs/en_struct_descriptions.go, internal/data/data_manager.go, internal/data/data_manager_test.go, internal/database/sqlcommon/message_sql.go, internal/database/sqlcommon/message_sql_test.go, internal/events/aggregator.go, internal/events/aggregator_batch_state.go, internal/events/aggregator_batch_state_test.go, internal/events/aggregator_test.go, mocks/datamocks/manager.go, pkg/core/message.go, pkg/database/plugin.go
Proposal to add a "reject_reason" to messages (ie to database and API), which will be populated with the error text whenever a message is rejected. Previously this reason would only be logged, so the hope is that this assists in debugging when a message is rejected for an unexpected reason.
=> Surface message rejection reason to API

internal/database/sqlcommon/ffi_sql.go
When guessing the reason for an insert conflict, the query needs to exactly match the configured database indexes. That means that the "name" and "networkName" queries need to both include "version" as well, otherwise we risk grabbing a row that isn't actually a conflict.
Fixes #1347
=> Fix uniqueness check in InsertOrGetFFI to match indexes

internal/blockchain/fabric/fabric.go, internal/blockchain/fabric/fabric_test.go
Fabric chaincode events when dispatched to FabConnect by the Fabric SDK do not contain the index within the block:
https://github.com/hyperledger/fabric-sdk-go/blob/7af45cede6afa3939a9574bc9948cca9fb424257/pkg/common/providers/fab/eventservice.go#L43C1-L59
So the only information upon which to build a unique `ProtocolID` for the event is the block number, and the transaction index (noting Hyperledger Fabric has a restriction of one transaction per block).
Under load when multiple events are packed into a single block in Fabric, the FireFly Core code was de-duplicating them as a single event, because they all had the same `ProtocolID`, such as `000000000295/000000/000000` (where the second and third parts are always zeros).
=> FabConnect does not / can not set transactionIndex and eventIndex

go.mod, internal/assets/token_pool.go, internal/cache/cache.go, internal/cache/cache_test.go, mocks/cachemocks/manager.go
=> Remove token pools from the cache upon deletion

docs/gettingstarted/sandbox.md, docs/gettingstarted/setup_env.md
Adding two improvements in docs:
- adding a note for macOS users (port 5000 already in use)
- updating the command to be consistent with previous page (created `dev` stack but next page started `demo`)
=> Docs improvements

internal/blockchain/ethereum/ethereum.go, internal/blockchain/ethereum/ethereum_test.go
The payloads that flow between `firefly-core` and `firefly-evmconnect` are a very important contract in FireFly, and there's complex translation that happens (FFI <-> ABI etc. and other things in the operation like the `from` address and `location`).
For debugging it's very important to be able to see the exact payload, and important enough you shouldn't need to enable `trace` level and take the cost of logging _every_ payload exchange between microservices to see it.
=> Log full payload of critical EVMConnect actions at DEBUG level

docs/reference/types/subscription.md, docs/reference/types/wsstart.md, docs/swagger/swagger.yaml, internal/coremsgs/en_struct_descriptions.go, internal/events/webhooks/webhooks.go, internal/events/webhooks/webhooks_test.go, pkg/core/webhooks.go
So that you can configure the HTTP Proxy on a per-subscription setting, like you can with the mTLS certificates, or the other HTTP options
=> Add httpOptions.proxyURL option to Subscription

internal/blockchain/common/common.go, internal/blockchain/common/common_test.go, internal/blockchain/ethereum/ethereum_test.go, internal/blockchain/fabric/fabric_test.go
This ensures the namespace can be accurately extracted.
Fixes https://github.com/hyperledger/firefly/issues/1374
=> Correctly parse blockchain subscription name when delivering events

docs/reference/config.md, go.mod, go.sum, internal/apiserver/route_get_events_test.go, internal/apiserver/route_get_msgs_test.go, internal/database/sqlcommon/message_sql_test.go
Validates proper escaping of '%' and '_'.
Requires https://github.com/hyperledger/firefly-common/pull/87
Fixes #1084
=> Add unit test for LIKE filters with escaped characters

internal/events/blockchain_event.go, internal/events/blockchain_event_test.go, internal/events/token_pool_created_test.go, internal/events/tokens_approved_test.go, internal/events/tokens_transferred_test.go, internal/txcommon/txcommon.go, internal/txcommon/txcommon_test.go, mocks/txcommonmocks/helper.go
If an existing blockchain event is found, be sure to look up and use the existing ID when inserting token transfers/approvals.
Fixes #1385
=> Prevent inserting token transfers with invalid blockchain event refs
